### ISSUE TITLE
Spikes for extension infrastructure 

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1034]
Per discussion with @kjdelisle and @raymondfeng, created this epic. 

- to make sure we have consistent extension points/extension
- Raymond has a few PRs created

## Scope (for 4.0 GA)

For GA, do a spike story to confirm feasibility of each of the following extension use cases:

- [ ] Custom booters - #1461
- [ ] Custom authorization providers & strategies - #1462
- [ ] Custom validators and serializers/deserializers for REST layer - #1463
- [ ] How to apply environment-specific operational configuration - #1464

**Comment by raymondfeng** [comment]
Related PRs:

- Extensibility
  - https://github.com/strongloop/loopback-next/pull/657 (Implement extension point/extension pattern with Context)
  - https://github.com/strongloop/loopback-next/pull/983 (Add configuration for extension points/extensions)

- Composability:
  - https://github.com/strongloop/loopback-next/pull/992 (Allows extension points/extensions to be decorated with corresponding metadata)
  - https://github.com/strongloop/loopback-next/pull/929 (Allow a component to expose a list of bindings)
  - https://github.com/strongloop/loopback-next/pull/882 (Allow multiple contexts to be composed into a hierarchy)
- https://github.com/strongloop/loopback-next/pull/713 (Allow automatic composition of actions)

**Comment by raymondfeng** [comment]
Some context from the `@loopback/boot` discussion:

A typical LoopBack 4 application will be composed from multiple components. A component is the basic unit and it has both deployment and runtime views. The deployment view is module while the runtime view is context. A component can be the main application module, an embedded local module, or an installed npm module. I want to have main component to represent the application module to make it consistent. The relation is illustrated below:

![App](https://user-images.githubusercontent.com/540892/35754757-7f7b5d60-0819-11e8-9bbc-10c25dfde8a7.png)

Each component can have declarative artifacts as well as programatic contributions. The bootstrapper can boot components so that declarative constructs can be populated in the context. The boot process connects the deployment view to the runtime view.

The Application coordinates the composition of components. For example, app.boot() will locate a list of components (including the main one by the application module) and use the Bootstrapper to boot the components. Please note each component has a reference to the containing module and corresponding metadata from package.json or other files. The module metadata provides configuration such as project root and project layout version for the boot. An instance of Context is created per component. After boot, the component context is fully populated. The application can then compose all component contexts into app context (by merging or delegations).
