### ISSUE TITLE
Robust HTTP processing capabilities (DP3)

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1038]
Based on discussion with @raymondfeng @kjdelisle: 
We need robust HTTP processing capabilities to deal with HTTP layer policies
  - e.g. CORS, compression/decompression, content negotiation.

@raymondfeng 's initial investigation:
- we don't want to take the burden to implement the HTTP stack.
- base functionality from node core is not good enough
- Possibility is:
   - to use Express base without routing plus the common middleware
    - or we can use Koa

## DP3 scope

- Must have: rework internals to use Express request/response types
- Leverage CORS middleware instead of the current workaround (minimal refactoring)
- HttpEndpointFactory - a new module to deal with HTTP(S) setup, a dependency of `@loopback/rest`
- Stretch goal: serving OpenAPI spec document should be implemented in a controller method

## Out of scope

- Local API Explorer (Swagger UI) should be implemented using Express middleware
- Expose Express to app developers, allow them to add custom middleware

### Additional Information
- Spike: #1071 
   - See spike outcome and discussion starting from this: https://github.com/strongloop/loopback-next/issues/1071#issuecomment-380241710

Relevant: https://github.com/strongloop/loopback-next/issues/180

**Comment by bajtos** [comment]
Yesterday, we reviewed DP3 scope for this epic with @raymondfeng and @dhmlau and decided on the following feature set:

- Must have: rework internals to use Express request/response types
- Leverage CORS middleware instead of the current workaround (minimal refactoring)
- HttpEndpointFactory - a new module to deal with HTTP(S) setup, a dependency of @loopback/rest
- Stretch goal: serving OpenAPI spec document should be implemented in a controller method

**Comment by bajtos** [comment]
> Must have: rework internals to use Express request/response types 

This is mostly #1292 and #1326.

#436 IS NOT related.

> Leverage CORS middleware instead of the current workaround (minimal refactoring)

I'd like to send a pull request today, I am not sure if we need a story.

> HttpEndpointFactory - a new module to deal with HTTP(S) setup

This is tracked by #1331 with a follow-up in #430.

> Stretch goal: serving OpenAPI spec document should be implemented in a controller method (#1332)

This is correct.

I added one more story to the epic - Blog post: Leveraging Express for a more robust HTTP processing #1337.

**Comment by bajtos** [comment]
> Leverage CORS middleware instead of the current workaround (minimal refactoring)

See https://github.com/strongloop/loopback-next/pull/1338

**Comment by dhmlau** [comment]
ok. Summarize what we have here.  
- [x]  Must have: rework internals to use Express request/response types (~#1292, #1326~)
- [x] Leverage CORS middleware instead of the current workaround (minimal refactoring) (#1338) 
- [ ] 🏃HttpEndpointFactory - a new module to deal with HTTP(S) setup, a dependency of (tracked by #1331, with out-of-scope follow-up task #430)
- [ ] Stretch goal: serving OpenAPI spec document should be implemented in a controller method (#1332)
- [ ] Blog post: Leveraging Express for a more robust HTTP processing #1337

@hacksparrow @bajtos, does it look good to you?

**Comment by bajtos** [comment]
@dhmlau LGTM 👍

**Comment by dhmlau** [comment]
Closing as done.
