### ISSUE TITLE
Monthly Milestone - April 2018

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1044]
The goal for this month should be:
- finish off items for Developer Preview 2 release (high priority)
- work on spikes that help us to create backlog for the next release

## Goals
**Developer Preview 2 Items**
- [x] openapi-v3-spec module: add basic tests #181 
- [x] Enhance Repository Mixin to provide a repository getter #745 
- [x] Inject repositories registered via app.repository() API #744 
- [x] 🏃 Consistent file naming style #612 
- [x] ~[Docs] Sidebar reorganization #731~ CLOSED as no longer irrelevant

**Spikes**
- [ ] 🏃  Juggler relation spike [SLIPPED](https://www.youtube.com/watch?v=SrDSqODtEFM) #995 

## Stretch Goals
**Spikes** 
  - [x] Weakly typed integration spike #1069
         - @raymondfeng has done spike #1119.  Need a meeting to discuss the spike finding.
  - [x] Use Express / Koa for HTTP processing #1071 
          - @raymondfeng has a spike PR #1082 
               - need a meeting to discuss the spike finding, so that we can build the backlog.
  - [x] [SPIKE] Create `@loopback/boot` to support declarative JSON/YAML  #441 
  - [x] Validation and type conversion at REST/Model/Database layer #1057 
  - [ ] [Spike] Express vs. Koa for HTTP processing #1255 
  - [x] [CLI] Show list of all available commands in help #934

Other PRs
  - [x] [CLI] Move away from using master to clone examples via `lb4 example` https://github.com/strongloop/loopback-next/issues/1120
  - [x] [Docs] Local Site Scaffolding https://github.com/strongloop/loopback-next/issues/1232
      - This enabled testing `@loopback/docs` in LB4 as well. 
  - [x] feat: upgrade to openapi3-ts@0.11.0 https://github.com/strongloop/loopback-next/pull/1265
  - [x] chore: add a sandbox location to enable testing w/ source code https://github.com/strongloop/loopback-next/pull/1252
  - [x] Introduce strongly-typed metadata key https://github.com/strongloop/loopback-next/pull/1240
  - [x] refactor: move example packages to examples folder https://github.com/strongloop/loopback-next/pull/1231
  - [x] [RFC] refactor(docs): move apidocs to `/docs` https://github.com/strongloop/loopback-next/pull/1207
  - [x] feat(testlab): update sourceMappingURL when copying a JS file https://github.com/strongloop/loopback-next/pull/951
  - [x] chore: make the code compatible with node 10.0.0 https://github.com/strongloop/loopback-next/pull/1281
  - [x] lb3 feat(loopback-datasource-juggler): add omit default embedded item flag for embedsMany relation https://github.com/strongloop/loopback/issues/2882
  - [x] Replace type definition being imported by `repository-json-schema` #1132 

Legend of annotations:

Mark|Description
--|--
🏃 | work in progress
✋ | blocked task

**Comment by dhmlau** [comment]
Removed `Bring questions back to GitHub, use GG only for announcements #47` as part of the stretch goal for [March milestone ](https://github.com/strongloop/loopback-next/issues/937)

**Comment by virkt25** [comment]
Removed `App template generates MIT License file without prompt #1079` since it was done in March as a stretch goal.

**Comment by b-admike** [comment]
We have reached the end of April. Closing this ticket.
