### ISSUE TITLE
Dev Preview #2 release checklist

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1059]
## Overview 
When we're ready to ship Developer Preview #2, we need to refresh/announce the status change of LoopBack 

## Acceptance Criteria
- [ ] update READMEs(update the ones that has the status) in LB4 monorepo
  - change `Status: Developer Preview #1` to `Status: Developer Preview #2`
- [ ] update loopback.io
  - at the top of the page, it says `LoopBack 4 is currently in Developer Preview #1 release.`. 
- [ ] announcement blog
  - objectives for DP2
  - what's new (highlight diff between DP1 and DP2)
  - what's next 
  - see the announcement blog for `Dev Preview #1`: https://strongloop.com/strongblog/loopback-4-developer-preview-release

- [ ] Publish packages to npmjs

**Comment by dhmlau** [comment]
blog post working in progress: https://github.com/strongloop/strongloop.com/pull/121
