### ISSUE TITLE
Make services easy to test + docs

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1311]
_This is a follow-up for https://github.com/strongloop/loopback-next/issues/1267_

When consuming a service using REST connector with template-based configuration: As an app developer, I would definitely want to have few smoke tests to verify that my templates work as intended and match the API provided by the service at the other side. I would like to write an integration test that's using only the service (not the full app!), something along the following lines:

```ts
import {GeoService} from '../services/geo.service';
import {expect} from '@loopback/testlab';

describe('GeoService', () => {
  let service: GeoService;
  beforeEach(() => service = new GeoService());

  describe('geocode', () => {
    it('returns geo coords for a given address', () => {
      const result = await service.geocode('107 S B St', 'San Mateo', '94401');
      // { lat: 37.5669986, lng: -122.3237495 }
     expect(result.lat).approximately(37.5669986, 0.5);
     expect(result.lng).approximately(-122.3237495, 0.5);
    });
  });
});
```

## Acceptance criteria

 - [x] Finish #1364 implementing an aggressive caching HTTP proxy to speed up integration tests.
 - [x] Finish #1347 which is adding Geocoder service to Todo example to demonstrate in practice our advices regarding Service testing.  Leverage the caching HTTP proxy to keep `npm test` fast enough. The tricky part: how to configure the Service datasource to use our proxy in the test, but not in production? A poor-man's workaround that may work until we implement proper support for per-env config: the tests can use `process.env.PROXY` to instruct the underlying `request` module which is backing our service connectors like loopback-connector-rest. 
 - [x] Update [Todo tutorial](http://loopback.io/doc/en/lb4/todo-tutorial.html) - describe how to add Geocoder service - see #1441
 - [x] http://loopback.io/doc/en/lb4/Testing-your-application.html#unit-test-your-services: we are not going to write any unit tests for services right now, this section should be removed - see #1445
 - [x]  http://loopback.io/doc/en/lb4/Testing-your-application.html#test-your-services-against-real-backends: add content explaining users how to write integration tests, see the code example above for inspiration - see #1445
 - [x]  http://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html: add a section about testing services, point readers to best-practices section "test-your-services-against-real-backends". We may need to change the prescribed way of defining Services to make testing easier - see #1445

**Comment by shimks** [comment]
Is this a proposal on the service we generate through the CLI tooling?

**Comment by bajtos** [comment]
FWIW, I have already started to look into implementing this user story.

**Comment by shimks** [comment]
@bajtos For the dev experience of writing integration tests, is something like this sufficient enough? https://github.com/strongloop/loopback-next/blob/master/packages/service-proxy/test/integration/service-proxy.integration.ts. If it isn't, what kind of other functions should we provide so that the users may be able to write their tests more easily?

**Comment by bajtos** [comment]
IMO, the example tests in `service-proxy.integration.ts` require the app to share the implementation of the service in many places (inject decorators, integration tests, etc.). Ideally, I'd like both tests and controllers to share the same implementation details of a service.

> what kind of other functions should we provide so that the users may be able to write their tests more easily?

That's something I am trying to figure out in #1347. My conclusion so far is that the story "Make services easy to test + docs #1311" is not well defined yet and we need a spike (which I am working on in #1347).

**Comment by dhmlau** [comment]
@bajtos , since this is in the June milestone, we'd like to get it estimated soon.  Is the acceptance criteria good for estimation?  From the above comment, it seems like we might need to modify? thanks.

**Comment by bajtos** [comment]
@dhmlau added two more items to the acceptance criteria. LGTY now?

**Comment by bajtos** [comment]
Done 🎉
