### ISSUE TITLE
Router cleanup

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#135]
The current implementation of SwaggerRouter is rather messy, I'd like to clean it up before adding any new functionality.

  - Decompose SwaggerRouter class into small functions that can be composed in various ways, this should eventually allow us to implement ideas in https://github.com/strongloop/loopback-next/issues/113 - Let's do this as part of the work on decomposition.
 - [ ] Move code and tests to new repositories:
   - [x] typed swagger spec - see https://github.com/strongloop/loopback-next/pull/177
   - [x] swagger-spec builder - see #187
   - `@loopback/router` - ~~see #227~~ - This does not make sense now, it looks like we need more fine-grained packages (route lookup as a function, argument parsing as a function, etc.)
- Rework tests to use `supertest` instead of `request`. Request's interface is already showing limitations, it's time to move to something better while the amount of needed changes is low - move to #237
- Consider adding `supertest` to `testlab`, this makes sense when we also add helpers for setting up HTTP server for a loopback app/router and returning a supertest instance connected to that server - moved to #237
- Write a simple benchmark to get an idea how performant our solution is. This will allow us to compare performance of different designs, e.g. the `ctx.get`-based proposal in https://github.com/strongloop/loopback-next/issues/113 - I think it's too early for this, considering how fluent and uncertain the router design still is.

**Comment by bajtos** [comment]
Scoped to 1 story point for Sprint 34.
