### ISSUE TITLE
Monthly Milestone - June 2018

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1375]
### LB4 Goals

- Finish HTTP hardening story #1038
    - [x] HttpEndpointFactory #1331 
    - [x] Describe how to use Shot Request/Response mocks #760 - see #1393
    - [x] Blog post: Leveraging Express for a more robust HTTP processing #1337

- Finish Integration with REST/SOAP services #1036
    - [x] Make services easy to test + docs #1311 

- Model Relations #1032 - complete the `hasMany` relation story
     - [x] Retrieval of related model for a `HasMany` relation #1372 
     - [x] Add all remaining HasMany methods. #1376 
 
- Boot, CLI, declarative support  
  - [x] [CLI] Generating `index.ts` in each models/repositories/controllers automatically #1127 (see https://github.com/strongloop/loopback-next/pull/1363)
  - [x] [CLI] Generate DataSource #1225 (see https://github.com/strongloop/loopback-next/pull/1385)

- Validation and Type Conversion #755 
   - [x] Use OpenAPI v3 spec to coerce primitives in query, path and headers #750 (see https://github.com/strongloop/loopback-next/pull/1370)

### LB4 Stretch Goals 
**UPDATE (6/12)**: stretch goals are updated as some tasks are removed out of DP3.  

- Model Relations #1032
    - [x] Add tests for `hasMany` relation source code #1379
    - [ ] incorporating relations in examples #1358
    - [x] Refactoring: Remove execute function out of Repository interface #1355
    - [ ] ~Split Repository interface into different interfaces #1356~

 - Validation and Type Conversion #755
    - [ ] Router: validate input parameters #118 
    - [ ] ~Make coercion and validation work off of @loopback/types #1319~
    - [ ] ~Implement coercion between HTTP and LB4 layers #1306~ 
    - [ ] ~Allow coercion and validation to be extensible #1343~
   
- Misc
    - [x] Todo Tutorial Feedback -- Issues, Comments, Challenges #1206
        - The task is to create stories mentioned in the epic 
    - [x] Clean up "Best Practices with LoopBack 4" #1094 
    - [ ] [CLI] Generate model #1221       
    - [x]  Move `Concepts` section out of `@loopback/repository`'s README and into the `docs` folder #1137
    - [x] Enable tsc watch in projects scaffolded by lb4 CLI tool #1259
    - [ ] ~Add Code Climate Tool #1087~
    - [x] [CLI] Remove the automatic "Controller" suffix from the controller command #886

### LB3 Goals
- [x] Safefields doesn't work with "array of errors"https://github.com/strongloop/strong-error-handler/issues/45
- [x] Clarify which Database supports the LoopBack auto upgrade-migrate feature https://github.com/strongloop/loopback.io/issues/284

**Stretch goals**

- [x] Fix high-severity security vulnerabilities in generator-loopback https://github.com/strongloop/generator-loopback/issues/352

---
**Legend of annotations**

Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task

**Reference**
DP3 release: https://github.com/strongloop/loopback-next/issues/1330
~ - [ ] hasMany doc + blog #1351 ~ defer it to next milestone

**Comment by jannyHou** [comment]
@dhmlau As we discussed,  we already have committed 66 story points in total, I am afraid it's a little beyond our velocity, shall we move some committed stories into the stretch goal? I would suggest the two relation tasks that not estimated yet, and the validation story with 13 points:

-  incorporating relations in examples #1358 (needs estimate)
- Use relational decorators' metadata to construct constrained target repository instance on relational properties #1354 (needs estimate)
- Router: validate input parameters #118

thought @strongloop/lb-next-dev ?

**Comment by bajtos** [comment]
+1 to reduce the scope.

As for relations, I think we should remove "hasMany doc + blog #1351" instead of one of the coding story, because the blog should be the last story in the epic to work on.

**Comment by dhmlau** [comment]
+1 in removing "hasMany doc + blog" #1351 in june milestone.  
At first I was thinking it might be good to move to stretch goals, but given the amount of work needed to be done in this epic, we may not be able to contain it at all.

**Comment by b-admike** [comment]
I'm okay to leave #1351 out of the milestone and possibly #1358 as a stretch goal.

**Comment by jannyHou** [comment]
Thanks for all suggestions, l modified the list according to our chat above, I moved #1358 to stretch goal, and deferred the blog issue #1351 to next milestone.

cc @dhmlau @b-admike @bajtos 

And any objection on moving "Router: validate input parameters" #118 into the stretch goal?
@strongloop/sq-lb-apex @raymondfeng @bajtos ?

**Comment by bajtos** [comment]
@jannyHou the changes you made are fine.
