### ISSUE TITLE
DP3 Release checklist

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1377]
Getting it from the release checklist: https://github.com/strongloop/loopback-next/wiki/Release-Checklist

- [x] update `README.md` in `loopback-next`
  - change `Status: Developer Preview #2` to `Status: Developer Preview #3`
- [x] update loopback.io
  - at the top of the page, it says `LoopBack 4 is currently in <some release>`.
- [x] Publish packages to npmjs
  - For repo list, see https://github.com/strongloop/loopback-next/blob/master/MONOREPO.md
- [x] announcement blog post
  - Content contains:
    - objectives of this release
    - what's new (diff from `<old release>` to `<new release>`)
    - what's next
  - example blog post: https://strongloop.com/strongblog/loopback-4-developer-preview-release
