### ISSUE TITLE
[EPIC] Model Relations (4.0 GA)

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1421]
## Description / Steps to reproduce / Feature proposal

This is the Model Relations epic for GA release, and includes the following the relation types:
- [x] BelongsTo #1361

**Stretch goals**
- [ ] CLI tooling (`lb4 relation`) #1359
- [ ] Split Repository interface into different interfaces #1356
- [ ] HasOne #1422 (moved to stretch goals by @bajtos @raymondfeng and @virkt25 on 2018-08-28)

**Out of scope**
- HasManyThrough
- HasAndBelongsToMany
-  Polymorphic
-  EmbedsOne
-  EmbedsMany
-  ReferencesMany

_Note:_ The last four relation types above had lots of issues in LB3.  We need to rethink the design.  

**What we have for DP3**
- HasMany
