### ISSUE TITLE
Sugar API for registering services + automated registration via boot

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1439]
At the moment, `@loopback/boot` is able to automatically load datasources and model repositories from project files. We should add support for loading services too.

See  #1347 for an example implementation.

## Acceptance criteria

- [x] Implement a mixin adding `app.service` API, this mixin should be provided by `@loopback/service-proxy`. Proposed implementation (see #1347):

    ```ts
    service<T>(provider: Constructor<Provider<T>>) {
      const key = `services.${provider.name.replace(/Provider$/, '')}`;
      this.bind(key).toProvider(provider);
    }
   ```

    (PR #1649, the method name is called `serviceProvider`.)

- [x] Update the CLI template to apply this new mixin to all newly created applications - PR #1649

- [x]  Add a new booter for loading services from files matching the following naming convention: `services/${name}.service.js` - PR #1652

- Update/simplify `examples/todo` to use this new functionality 
  - [x] use the new mixin - PR #1649 
  - [x] use automatic registration via boot

- [x] Document the new booter in [Booting an application](http://loopback.io/doc/en/lb4/Booting-an-Application.html)

- Update/simplify the content in the relevant [Todo Tutorial](http://loopback.io/doc/en/lb4/todo-tutorial.html) section to leverage the new booter
  - [x] use the new mixin - PR #1649 
  - [x] use automatic registration via boot

**Comment by bajtos** [comment]
> Proposed implementation (see #1347):
>
> ```ts
> service<T>(provider: Constructor<Provider<T>>) {
>   const key = `services.${provider.name.replace(/Provider$/, '')}`;
>   this.bind(key).toProvider(provider);
> }
> ```

I am proposing to call the new method `serviceProvider` in order to avoid possible confusion about the type passed to the sugar API (a Provider vs. a service class), because other sugar-API methods like `controller`, `repository` and `dataSource` are accepting a class constructor.
