### ISSUE TITLE
[Epic] KeyValue repository

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1447]
So far, LB4 persistence story is all about CRUD. Key-value stores are another common scenario we should support.

LoopBack 3.x introduced KeyValue API and Redis + eXtremeScale connectors.

For LoopBack 4, we need to add Repository implementations for KeyValue API and verify that all pieces work together as expected.

## Scope

- [x] Add necessary Repository APIs and implementations (#1539)
- [x] Verify the use case against real Redis instance (#1481)
- [ ] CLI support (#1588)
- Docs
  - [x] Documentation (#1654)
  - [x] Example app (https://github.com/strongloop/loopback4-example-shopping/pull/4)
  - [ ] Blog post

The use case to drive the features: a "shopping cart" component used on an e-shop platform like Walmart.

**Comment by raymondfeng** [comment]
Adding docs - https://github.com/strongloop/loopback-next/pull/1654

**Comment by dhmlau** [comment]
The docs task has been created and PR has merged.  Closing this task as resolved.
