### ISSUE TITLE
[EPIC] Validation and Coercion (4.0 GA)

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#1456]
This epic continues where the previous one finished: #755.

Support "new user sign up" story. Interesting cases: the provided email address must be unique and also a valid email per RFC spec.

- Validate and coerce most OpenAPI parameter/data types
- Validate (and coerce?) complex request bodies as described by JSON Schema subset supported by OpenAPI.

## Scope

P1
- [ ] #100 Router: coercion of complex parameters from string sources
- [ ] #1112 Generate OpenAPI schema for Model properties of built-in JavaScript/Node.js types 
- [ ] #1590 Cache pre-compiled AJV validators 

P2
- [ ] #1319 make coercion and validation work off of `@loopback/types`
- [ ] #435 Spike: Resolve `$ref` in api/controller/route specs
