### ISSUE TITLE
Monthly Milestone - July 2018 🌾

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1477]
## July Milestone

General theme: 
- Finish DP3
- Start spiking on GA, if possible

### LB4 Goals
- [x] HTTP Hardening epic  #1038 
   - [x] Handle IPv6 localhost URLs in http-server package #1453  (if not done in June)
   - [x] Support HTTPS #430  (if not done in June)
- [x] Model relation #1032
   - [x] blog post and docs #1351 
   - [x] Incorporating relations in our examples #1358
   - [Relation] Support BelongsTo relation #1361  (p2 item)
- [x] Validation and Type conversion #755
   - [x] Router: validate input parameters #118 (blocked #750)
- [x] Other DP3 items (not in any epic)
   - [x] Creating Express mode for generating applications(must have) and other artifacts(optional) through CLI https://github.com/strongloop/loopback-next/issues/1340
   - [x] CLI for Model #1221
   - [x] Document how is the CLI generator discovering models and repositories in the project #1085
   - [x] DP3 release checklist #1377  
   - [x] @loopback/rest: HttpHandler integration test times out after 2 seconds randomly #1407
   - [x] [Spike] Give bottom-up examples in Controllers.md, Routes.md, Repositories.md and Decorators.md #1173
   - [x] ~apidocs links are broken and anchors are non-descriptive #1413~ done in June milestone

### LB4 Stretch Goals - Spikes for GA
- Spike: Deploy LB4 application to IBM Cloud #1446
- Spike: Spike: KeyValue repository #1448

### LB3 Stretch Goals 
- [ ] 🏃 Default sort order may impact performance on some queries https://github.com/strongloop/loopback-connector-mongodb/issues/55
- [ ] PersistedModel.destroyAll has very dangerous behaviour if the filter is not passed in correctly. https://github.com/strongloop/loopback/issues/3094
- [x] Fix test suite https://github.com/strongloop/generator-loopback/issues/354
- [ ] Upgrade yeoman-generator to latest https://github.com/strongloop/generator-loopback/issues/355

**Legend of annotations**

Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
