### ISSUE TITLE
@authenticate implementation

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#150]
Closes #99, closes #100, closes #95 

As a user, I should be able to specify which controller methods require authentication via `@authenticate`.

- [x] Spike into learning how to create decorators (annotations) in TypeScript and Reflect.get/setMetadata (timebox to 2 hours)
  - [x] @mpatsute strongloop-internal/scrum-asteroid/issues/99
  - [x] @siddhi strongloop-internal/scrum-asteroid/issues/100
- [x] Implementation | strongloop-internal/scrum-asteroid/issues/95 @siddhipai @mpatsute 
- [x] [Update the LBn-example](https://github.com/strongloop/loopback-next/issues/145) @rashmihunt

**Comment by ritch** [comment]
The tricky part about this implementation is that it will determine whether or not the controller method will be invoked...

Also keep in mind that...
`@authenticate` will ONLY add some metadata to a controller method that it should be authenticated.... when we (router, core, etc) goes to execute the controller method, it should first check if authentication is required and only execute the method if

- authentication is not required
- authentication is required and valid credentials have been provided

**Comment by ritch** [comment]
The implementation of `@authenticate` will be trivial AFAICT:

```ts
// poor mans impl
function authenticate() {
  return function(controllerMethod) {
    Reflect.setMeta('authenticate', true, controllerMethod);
  }
}
```

**Comment by ritch** [comment]
```ts
// this is provided by loopback core
// aka a built-in binding
// this should be re-bound by the authentication package
app.bind('authentication.authorized').to(() => {
  return true;
});

// in the router or whever
// ...about to call controller[method].apply(...);

function invoke(@inject('authentication.authorized') authorized) {
  if (authorized) {
    // execute the method
    controller[method].apply(...);
  } else {
    // reject somehow
  }
}
```

**Comment by ritch** [comment]
Basic implementation of the meaty parts:

```ts
// in our authentication package
app.bind('authentication.authorized').to((@inject('controllerMethod') controllerMethod, @inject('authentication.user') user) => {
  if (Reflect.getMetadata('authenticate').value === true) {
    if (user) {
      return true;
    } else {
      return false;
    }
  } else {
    return true;
  }
});
```

**Comment by ritch** [comment]
Only thing missing here is that the `Router` has no idea about `authentication.authenticated`

**Comment by bajtos** [comment]
Closing as done.
