### ISSUE TITLE
username/password Authentication Bindings

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#151]
As a user of the authentication package, I should be able to get the username and password provided by the client, so that I can lookup user data and verify passwords.

- [x] Determine how to get username/password from [passport strategy](https://github.com/jaredhanson/passport-http/blob/master/lib/passport-http/strategies/basic.js)
- [x] Impl `authentication.credentials.username` binding using passport strategy
- [x] Impl `authentication.credentials.password` binding using passport strategy
- [x] Unit / int tests

**Comment by rashmihunt** [comment]
closing as  strongloop-internal/scrum-asteroid#91 existed and this is a duplicate

**Comment by ritch** [comment]
@rashmihunt look into https://github.com/jaredhanson/passport-strategy and determine if we can bind `authentication.password`.

**Comment by rashmihunt** [comment]
Results/findings

Determine how to get username/password from passport strategy

- I was able to use basic strategy(passport-http) and passport to authenticate loopback-example-facade accounts example end to end.
- Instead of passport, this code can use Deepak's wrapper, authenticate.ts from the PR or some other equivalent of this. This wrapper eliminates usage of 'passport 'module and also has capability for  getting strategy.success and strategy.failed

Determine how to get username/password from passport strategy
- There is no way to get username/password from strategy. Only way is to check for strategy.success or strategy.failed from Deepak's passport wrapper. If success, the username/password is what's in the http request. 

 Impl authentication.credentials.username binding using passport strategy
 Impl authentication.credentials.password binding using passport strategy

Based on the findings. the design is slightly changed.  See https://github.com/strongloop/loopback-next/issues/155

 Unit / int tests
- Have a working test case in accounts micro service in
