### ISSUE TITLE
Registering Components

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#152]
- [ ] Acceptance tests / criteria
- [ ] Docs
- [ ] Will we go with @app.bind vs @bind?
- [ ] Will we use `app.controller()` and `app.binding()` style or some generic version eg. `app.extension()`?
- [ ] impl

_From @ritch on April 13, 2017 17:47_

As an extension developer I should be able to write components (extensions) in a way that is discoverable / register-able by an application developer.

Something like this:

```ts
// my-extension
export myDecorator() {
  return (name) => {
    console.log(fn.name)
  }
}

@bind('foo')
export myBindiing() {
  return 'foo';
}
```

```ts
import {myBindiing} from 'my-extension';
let app = new Application();
app.binding(myBindiing);
```

...this is just a starting point. We also need to support easily registering:

 - `Controller`s
 - `Model`s
 - `Repositories`
 - etc

_Copied from original issue: strongloop-internal/scrum-asteroid#98_

**Comment by superkhau** [comment]
Closing via https://github.com/strongloop/loopback-next/pull/359, and we can already register components during Application construction (ie. `new Application({components: [...]});`)
