### ISSUE TITLE
Change TodoController in Todo/TodoList examples to the one generated by `lb4 controller`

### ISSUE THREAD

**Issue by shimks** [strongloop/loopback-next#1558]
## Description / Steps to reproduce / Feature proposal

To make the tutorial process streamline, we should go from manually defining the controller methods to have it be automatically generated from the CLI.

## Acceptance Criteria
- [x] remove the current `todo.controller.ts` and replace it with the one generated by the CLI
  - [ ] replace the tests as well
- [x] address the changes in the tutorial as well
  - [ ] find a way to keep the useful information in https://loopback.io/doc/en/lb4/todo-tutorial-controller.html or remove them entirely

**Comment by dhmlau** [comment]
@shimks , looks like we've modified this tutorial.  Could you please check if this ticket still valid?  Thanks.

**Comment by shimks** [comment]
@dhmlau Could you specify what the modification was?

**Comment by dhmlau** [comment]
it looks like that page still needs to be updated.

**Comment by dhmlau** [comment]
Marking it as LB4 GA `p1` item because i think we should have the docs fixed.  
@bajtos , feel free to modify if you disagree. Thanks.

**Comment by dhmlau** [comment]
@b-admike , i think this goes with the QuickLab you're working on.

**Comment by b-admike** [comment]
@dhmlau yes, but now that we have your PR (https://github.com/strongloop/loopback-next/pull/1846), maybe some of the items in the acceptance criteria can be checked off. I've checked off what I think is applicable.

**Comment by dhmlau** [comment]
Resolved by #1846
