### ISSUE TITLE
Document Built In Bindings (Reserved Binding Keys)

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#156]
As a user, I want to be able to inject basic metadata provided by the core framework, so that I can build extensions and applications that don't worry about low level details.

- [ ] [Come up with list of initial bindings](https://github.com/strongloop/loopback-next/issues/157)
- [ ] [Decomposed Router Design](https://github.com/strongloop/loopback-next/issues/149)
- [ ] [Order Independent Binding Resolution](https://github.com/strongloop/loopback-next/issues/143)

## Built in bindings (TBD):
### HTTP

| Name                 | Type                  | Description                            | Implemented By | Status |
|:---------------------|:----------------------|:---------------------------------------|:---------------|:------:|
| `req`                | `IncomingMessage`     | The raw http `Request`                 | Core           |        |
| `res`                | `Response`            | The raw http `Response`                | Core           |        |
| `req.verb`           | `HTTP.Verb` or `string`  |                                        | Core           |        |
| `req.baseUrl`        |                       |                                        | Core           |        |
| `req.cookies`        |                       |                                        | Core           |        |
| `req.hostname`       |                       |                                        | Core           |        |
| `req.ip`             |                       |                                        | Core           |        |
| `req.ips`            |                       |                                        | Core           |        |
| `req.method`         |                       |                                        | Core           |        |
| `req.originalUrl`    |                       |                                        | Core           |        |
| `req.params`         |                       |                                        | Core           |        |
| `req.path`           |                       |                                        | Core           |        |
| `req.protocol`       |                       |                                        | Core           |        |
| `req.query`          |                       |                                        | Core           |        |
| `req.secure`         |                       |                                        | Core           |        |
| `req.signedCookies`  |                       |                                        | Core           |        |
| `req.stale`          |                       |                                        | Core           |        |
| `req.subdomains`     |                       |                                        | Core           |        |
| `req.xhr`            |                       |                                        | Core           |        |
| `res.headers.get`    |                       |                                        | Core           |        |                                       
| `res.headers.set`    |                       |                                        | Core           |        |                                       
| `res.headers.clear`  |                       |                                        | Core           |        |                                         
| `res.cookies.get`    |                       |                                        | Core           |        |                                                                                                                                                
| `res.cookies.set`    |                       |                                        | Core           |        |                                                                                                                                                
| `res.cookies.clear`  |                       |                                        | Core           |        |                                                                                                                                                                                                                                   
| `res.jsonp`          |                       |                                        | Core           |        |                                  
| `res.jsonp.callback` |                       |                                        | Core           |        |                                           
| `res.links`          |                       |                                        | Core           |        |                                  
| `res.location`       |                       |                                        | Core           |        |                                     
| `res.redirect`       |                       |                                        | Core           |        |                                     
| `res.send`           |                       |                                        | Core           |        |                                 
| `res.sendFile`       |                       |                                        | Core           |        |                                     
| `res.sendStatus`     |                       |                                        | Core           |        |                                       
| `res.status`         |                       |                                        | Core           |        |                                   
| `res.type`           |                       |                                        | Core           |        |                                 
| `res.vary`           |                       |                                        | Core           |        |                                 


### Authentication / Authorization

| Name                           | Type                  | Description                            | Implemented By           | Status |
|:-------------------------------|:----------------------|:---------------------------------------|:-------------------------|:------:|
| `authentication.authenticated` | `Boolean`             | The provided credentials are valid     | @loopback/authentication |        |
| `authentication.authorized`    | `Boolean`             | Access is allowed                      | @loopback/authorization  |        |

**Comment by raymondfeng** [comment]
IMO, not controllers but also other artifacts, including extensions, should be able to receive injection from `ctx`. Is it possible to bind `ctx.*` to `app` so that `@inject('req.url')` and `@inject('res')` can work out of box?

**Comment by bajtos** [comment]
Now that #377 has been landed, I believe most of the request/response properties can be accessed via `#` separator. For example, `http.request#headers` to access the headers.

**Comment by bajtos** [comment]
Placeholder page: https://github.com/strongloop/loopback-next/wiki/Reserved-binding-keys

**Comment by virkt25** [comment]
@bajtos Can you PTAL. Updated to include the CONSTANT Variables. 

https://github.com/strongloop/loopback-next/wiki/Reserved-binding-keys/_compare/c2696a3c0e57cef99a42bd114204e11d7a99ffaa...5526e39d2cf9020378f97704cee9888e7698b6f4

**Comment by bajtos** [comment]
LGTM :

**Comment by virkt25** [comment]
Closing
