### ISSUE TITLE
Format the code using prettier

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#165]
I'd like to open a discussion about the coding style we using in LoopBack Next and more specifically, about automatically formatting all our source code using Prettier.

- Why Prettier: http://jlongster.com/A-Prettier-Formatter

- 1.0 announcement: http://jlongster.com/prettier-1.0

- Issue tracking TypeScript support: https://github.com/prettier/prettier/issues/13

~~Yes, I do realise Prettier does not support TypeScript yet, so this GH issue won't be actionable for a while.~~

What needs to be done:

 - [x] Move prettier config from `.vscode/settings.json` to `.prettierrc`, see https://github.com/strongloop/loopback-next/blob/06c787b01992c878b5aafb25a53c2cdbbeb5df42/.vscode/settings.json#L21-L25

 - [x] Add a build step to verify formatting, see https://github.com/prettier/prettier/issues/150#issuecomment-284197974 for starter

 - [x] Reformat all existing code using prettier (this may be a prerequisite for the previous step)

 - [x] Remove (disable) coding-style-related rules in tslint config, keep only rules catching programming errors

 - [x] Update developer docs - see https://github.com/strongloop/loopback-next/pull/1015
    - Mention that we use prettier (with link to relevant site)
    - Show how to fix prettier formatting errors using the npm scripts
    - Explain how to setup the VSCode extension for easy auto-formatting

 - Update all `loopback4-*` repos to use prettier too
    - [x] https://github.com/strongloop/loopback4-example-microservices - see https://github.com/strongloop/loopback4-example-microservices/pull/81
    - [x] https://github.com/strongloop/loopback4-extension-graphql
    - [x] https://github.com/strongloop/loopback4-extension-grpc
    - [x] https://github.com/strongloop/loopback4-extension-mqtt

**Comment by bajtos** [comment]
An existing prettier alternative: https://github.com/vvakame/typescript-formatter

**Comment by bajtos** [comment]
Prettier supports TypeScript now: https://github.com/prettier/prettier/releases/tag/1.4.0

**Comment by bajtos** [comment]
This task is basically blocked until prettier 1.6 is released (see https://github.com/prettier/prettier/issues/2589) and the VS Code extension supports sharing prettier configuration via a config file (see https://github.com/prettier/prettier-vscode/issues/124).

**Comment by bajtos** [comment]
`prettier@1.6.0` was released yesterday, a new version of `prettier-vscode` was released few minutes ago. We should be good to get this started!

**Comment by bajtos** [comment]
Done 🎉 🎊
