### ISSUE TITLE
Monthly Milestone - September 2018 🌾🌽🍂

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1653]
## September Milestone

Finish p1 items from the following epics:
- Spikes for Cloud Native (deployment to IBM Cloud) 
- E-commerce demo scenario
- Docs & a blog post for `HasMany` relation

Make progress in the remaining GA areas.

### LB 4.0

**Model Relations #1421**
- [ ] 🚶Support BelongsTo relation #1361 **=> PR #1618**

**e-commerce demo scenario #1476**
- [x] Shopping Cart Component #1481  (p2)
- [x] order history component #1483

**Spikes for Cloud Native Experience #1459**
- [x] 🚶Document how to deploy LB4 app to IBM Cloud via CloudFoundry #1604 **=> PR #1668**
- ~[ ] Blog about LB4 app deployment to IBM Cloud Cloud Foundry #1605 (p2) (TOB)~

**New web site design on LB4 #817**
- [ ] 🚶(Out of GA scope) ~Add a static site generator to reuse header and footer strongloop/v4.loopback.io#14~

**Validation and coercion #1456**
- [x] Router: coercion of complex parameters from string sources #100  **=> PR #1667**

**Spikes for extension infrastructure #1034**
- [ ] ~🚶Spike: Allow extensions to contribute custom authorization providers and strategies #1462 (TOD)~

**Miscellaneous**
- [x]  Add `lb4 repository` command #1588 **=> PR #1659**
- [x]  Unable to Explore API (generated OpenAPI spec is not valid) #1531 **=>PR #1655**
- [x]  Incorrect response codes for invalid HTTP calls #1469 **=> PR #1658**
- [x]  Create follow-up stories for KeyValue epic (finish the spike) #1448

### LB 3.x
- [x] Tests on node 10 fail the installation due to an update of memwatch-next(node-memwatch) https://github.com/strongloop/loopback-connector-mongodb/issues/451
- [x] Fix tests failing due to non-existent SOAP endpoints https://github.com/strongloop/loopback-soap/issues/14

### Stretch goals

**LB 4.0**
- [x] Cache pre-compiled AJV validators #1590
- [x] 🚶API Explorer does not work in Safari (mixed HTTP/HTTPS content problem) #1603 
- [ ] Add the doc for datasource migration #1547 (p2)
- [ ] Add Snyk to loopback-next #1516 (p2)
- [x] Consistent response format for PATCH/PUT #1471
- [x] Product Recommendation component #1482

**LB 3.x**
- [ ] 🚶PersistedModel.destroyAll has very dangerous behaviour if the filter is not passed in correctly. strongloop/loopback#3094
