### ISSUE TITLE
LoopBack 4 GA release checklist 

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1744]
When we're ready to release, here is the checklist:
- [x] (janny) update `README.md` in `loopback-next` [PR](https://github.com/strongloop/loopback-next/pull/1795)
  - change `Status: <old release>` to `Status: <new release>`
- [x] (janny)update loopback.io
  - at the top of the page, it says `LoopBack 4 is currently in <some release>`. [PR](https://github.com/strongloop/loopback.io/pull/746)

- [x] (diana) update v4.loopback.io **PR**=> https://github.com/strongloop/v4.loopback.io/pull/46

- loopback-datasource-juggler 4.0
  - [x] Create 3.x branch in juggler
  - [x] Start `loopback-datasource-juggler@4.0.0` development and drop support for Node.js 6.x in juggler - see https://github.com/strongloop/loopback-datasource-juggler/pull/1630
  - [x] Update LTS status in `master` READMe - see https://github.com/strongloop/loopback-datasource-juggler/pull/1633
  - [x] Publish `loopback-datasource-juggler@4.0.0` to npmjs
  - [x] Update LTS status in READMEs in 3.x and 2.x branches, publish new 3.x and 2.x versions. See https://github.com/strongloop/loopback-datasource-juggler/pull/1634 and https://github.com/strongloop/loopback-datasource-juggler/pull/1635
  - [x] Update `@loopback/repository` and `@loopback/service-proxy` to use this new version - https://github.com/strongloop/loopback-next/pull/1821
- [x] Publish all loopback-next packages to npmjs
  - For repo list, see https://github.com/strongloop/loopback-next/blob/master/MONOREPO.md
- [x] announcement blog post
  **PR**: https://github.com/strongloop/strongloop.com/pull/155 **Needs edit from @raymondfeng**
  - Content contains:
    - objectives of this release
    - what's new (diff from `<old release>` to `<new release>`)
    - what's next
    - LB 3.x is switching to Active LTS, 2.x to Maintenance LTS. Explain again what it means and mention dates when LTS ends for these releases.
    - Nothing changes for connectors, LB4 is fully compatible with existing connectors
  - example blog post: https://strongloop.com/strongblog/loopback-4-developer-preview-release

- [x] Update `loopback` 3.x and 2.x READMEs to mention their new LTS status, point users to LB4 as the new Current release line. Publish a new version of `loopback@2` and `loopback@3` to get updated READMEs to npmjs.
   **PR**:
     3.x: https://github.com/strongloop/loopback/pull/4022
     2.x: https://github.com/strongloop/loopback/pull/4023

- [x] Update description of 2.x/3.x versions of LoopBack in loopback-workspace. Publish a new version of workspace. PR: https://github.com/strongloop/loopback-workspace/pull/530

### Reference
Release checklist is originated from: https://github.com/strongloop/loopback-next/wiki/Release-Checklist

**Comment by virkt25** [comment]
I often learn about new frameworks, tools, etc. from Product Hunt. I think it would be a great place to promote the framework (but ideally it would be accompanied by the new website -- probably a good idea to promote using the current `v4.loopback.io` regardless). 

Link: https://www.producthunt.com/

**Comment by dhmlau** [comment]
@jannyHou will be creating PRs for the following items and won't merge until we're ready for GA:
- update README.md in loopback-next
 -  update loopback.io
 - update v4.loopback.io

**Comment by bajtos** [comment]
I added few more items related to juggler@4 release and also moved the long check-list of old loopback-related packages into a new issue https://github.com/strongloop/loopback-next/issues/1744. I think these updates are not blocking GA release and can be done in the days following the announcement.

**Comment by dhmlau** [comment]
LB4 GA is done! 🎉 
https://strongloop.com/strongblog/loopback-4-ga
