### ISSUE TITLE
Monthly Milestone - October 2018 🌦

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#1761]
## October Milestone
- Finish GA release! 
   - Complete all GA p1 items
   - GA p2 items as stretch goals
- After GA, focus on addressing users' feedback and helping early adopters to be successful

### LB 4.0
- [x]  BelongsTo, https://github.com/strongloop/loopback-next/issues/1361
- [x] Demo scenario - Order history component, https://github.com/strongloop/loopback-next/issues/1483
- [x] Demo scenario - Product recommendation component, https://github.com/strongloop/loopback-next/issues/1482
- [x] [REST] Consistent response format for PATCH/PUT, #1471
- [x] Cache pre-compiled AJV validators,  https://github.com/strongloop/loopback-next/issues/1590
- [x] 🚶Scaffolded LB4 app reports 404 for the home page, https://github.com/strongloop/loopback-next/issues/1745
- [x] LB4 release checklist, https://github.com/strongloop/loopback-next/issues/1744 and [Release] 🚀 4.0 GA 🚀 #1449

#### LB 4.0
- [x] Blog post on Thinking in LoopBack (Best Practices) https://github.com/strongloop/loopback-next/issues/639
- [x] Blog post for IBM Cloud deployment, https://github.com/strongloop/loopback-next/issues/1605
- [x] Change TodoController in Todo/TodoList examples to the one generated by `lb4 controller`, https://github.com/strongloop/loopback-next/issues/1558
- [ ] [Spike] HasMany relation to same Entity https://github.com/strongloop/loopback-next/issues/1682
- [x] 🚶Error handling for non-API routes https://github.com/strongloop/loopback-next/issues/1784
- [x] 🚶Invoke serve-static after API router https://github.com/strongloop/loopback-next/issues/1785
- [x] Add new extension property to hide controllers and routes from openapi.json #1874 
- [x] LB4 web site: Resources page https://github.com/strongloop/v4.loopback.io/issues/26
- [x] Add support for form request body https://github.com/strongloop/loopback-next/pull/1838

#### LB 3.x
- [ ] 🚶Focus on landing the mongodb connector PRs and release major version https://github.com/strongloop/loopback-connector-mongodb/issues/476

**Comment by jannyHou** [comment]
Here are the unfinished stories from September milestone, the priority of some may change, just in case we still want to work on them in October:

https://github.com/strongloop/loopback-next/issues/1605
https://github.com/strongloop/v4.loopback.io/issues/14
https://github.com/strongloop/loopback-next/issues/1462

Stretch goals:
https://github.com/strongloop/loopback-next/issues/1547
https://github.com/strongloop/loopback-next/issues/1516
https://github.com/strongloop/loopback/issues/3094

**Comment by dhmlau** [comment]
thanks @jannyHou.  
@jannyHou or @b-admike , could you please put the above list to the stretch goal for this month? Thanks!

**Comment by dhmlau** [comment]
Moved the slipped tasks to November milestone.
