### ISSUE TITLE
update(doc) Review tutorials to make use of latest cli options

### ISSUE THREAD

**Issue by marioestradarosa** [strongloop/loopback-next#1825]
## Description / Steps to reproduce / Feature proposal
reading tutorials, (ie: https://loopback.io/doc/en/lb4/todo-tutorial-repository.html ) 

## Current Behavior
 - I could see some missing features from the new cli options to enhance the developer experience. (_ie: to make a repository)_
-  There are some examples in the strongloop also, especially the microservices sample that is out-of-date compared to the latest breaking changes that were introduced lately

## Expected Behavior
To be updated as we move forward with features/enhancements, especially from the developer experience perspective

## Acceptance Criteria
Review the following tutorials to make sure they are up-to-date and update accordingly:
- [ ] todo tutorial 
  - Note: it is known that we need to include the latest cli commands, e.g. `lb4 repository.  @b-admike will update according to the QuickLab we'll have at Node+JS Interactive
- [ ] loopback4-example-microservices
- [ ] todo list tutorial
- [ ] SOAP web service tutorial

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@marioestradarosa , thanks for catching this!  Just wanted to let you know that we're almost done for GA, and everything else would be marked as `TOB` (top of backlog) which refers to what we'd like to do in the next 90 days.  

I've also turned this task into epics to break it down into smaller task.

**Comment by dhmlau** [comment]
This has been resolved as part of the effort from @nabdelgadir to review and update our documentation.  
For `loopback4-example-microservices`, we've decided to put our focus on the `example-shopping` (https://github.com/strongloop/loopback4-example-shopping).  Eventually, we'd like to expand the shopping example to have each components as microservices.
