### ISSUE TITLE
LB4 Documents need a cleanup pass

### ISSUE THREAD

**Issue by mhdawson** [strongloop/loopback-next#1908]
**Time boxed to 5 days**

## Description / Steps to reproduce / Feature proposal

Read through docs

Talked to maintainer and sounds like there is no active issue/planned work to complete docs.

## Current Behavior
Some TBDs and "work in progress" markings

## Expected Behavior
Complete doc 

### Specific sections include:

* TBD

``` txt
Roadmap.md:TBD.
Sequence.md:- [`Request`](http://apidocs.strongloop.com/loopback-next/) - (TBD) missing API
Sequence.md:- [`Response`](http://apidocs.strongloop.com/loopback-next/) - (TBD) missing API
```

* work in progress

``` txt
Controllers.md:{% include content/tbd.html %}
Model.md:{% include content/tbd.html %}
Sequence.md:{% include content/tbd.html %}
Sequence.md:{% include content/tbd.html %}
Sequence.md:{% include content/tbd.html %}
Sequence.md:{% include content/tbd.html %}
Testing-your-application.md:{% include content/tbd.html %}
Using-decorators.md:{% include content/tbd.html %}
```

* https://loopback.io/doc/en/lb4/Booting-an-Application.html

feels  a bit like a raw braindump.

## Acceptance Criteria
Go through all the pages in the [LoopBack 4 documentation](https://loopback.io/doc/en/lb4/index.html), listed below, and verify content and code snippets work and are up to date.

- [x] Getting started
- [x] Examples and tutorials
    - [x] Todo Tutorial
    - [x] TodoList Tutorial
    - [x] SOAP Web Service Tutorial
- [x] Key concepts
    - [x] Application
    - [x] Server
    - [x] Context
    - [x] Dependency injection
    - [x] Controllers. opened #2099
    - [x] DataSources
    - [x] Routes
    - [x] Sequence. opened #2100
    - [x] Model
    - [x] Repositories
    - [x] Relations - opened https://github.com/strongloop/loopback-next/issues/1910
    - [x] Decorators
    - [x] Error handling
- [x] How tos
    - [x] Exposing GraphQL APIs
    - [x] Deploying to IBM Cloud opened https://github.com/strongloop/loopback-next/issues/2033
- [x] Booting an Application
- [x] Using Components
- [x] Calling other APIs. opened https://github.com/strongloop/loopback-next/issues/2128
- [x] For current LoopBack users
- [x] Command-line interface
    - [x] Application generator
    - [x] Controller generator
    - [x] DataSource generator
    - [x] Model generator
    - [x] Repository generator
    - [x] Service generator
    - [x] OpenAPI generator
    - [x] Extension generator
    - [x] Download example
- [x] Best practices
    - [x] Defining the API using code-first approach
    - [x] Defining your testing strategy
    - [x] Testing your application. opened #2101
- [x] Extending LoopBack 4
    - [x] Creating Components
    - [x] Creating Decorators
    - [x] Creating Servers
    - [x] Testing your extension
- [x] Crafting LoopBack 4 - opened https://github.com/strongloop/loopback-next/issues/2020 
- [x] FAQ
- [x] Reference 
    - [x] Reserved binding keys
    - [x] Glossary
    - [x] Considerations for GDPR readiness

**Comment by dhmlau** [comment]
@mhdawson, thanks for catching this! 
Have the following plans for the examples you've pointed out.  Will update this task along the way. 
- [ ] Pages that contains `TBD`:
   - [ ] Roadmap.md:TBD.
       - suggest to either remove this page or link to the github issue https://github.com/strongloop/loopback-next/issues/1839
   - [ ] Sequence.md:- [`Request`](http://apidocs.strongloop.com/loopback-next/) - (TBD) missing API
       - navigating through the apidocs of the `rest` package, the `Request` brings to this link http://apidocs.loopback.io/@loopback%2fdocs/rest.html#Request but there is no content.  Need to investigate
   - [ ] Sequence.md:- [`Response`](http://apidocs.strongloop.com/loopback-next/) - (TBD) missing API
       - navigating through the apidocs of the `rest` package, the `Response` brings to this link http://apidocs.loopback.io/@loopback%2fdocs/rest.html#Response but there is no content.  Need to investigate

- [ ] Pages / sections that marks as `work in progress`:
   - [ ] Controllers.md:{% include content/tbd.html %}
      - need to look into the "review questions" the WIP pop up refers to. 
   - [ ] Model.md:{% include content/tbd.html %}
      - This page looks complete.  Should remove the first WIP note. Will review the 2nd WIP note in https://loopback.io/doc/en/lb4/Model.html#supported-json-keywords 
   - [ ] Sequence.md:{% include content/tbd.html %}
       - will create a separate task for the Sequence.md
   - [ ] Testing-your-application.md:{% include content/tbd.html %}
       - WIP pop up for https://loopback.io/doc/en/lb4/Testing-your-application.html#create-a-stub-service
   - [ ] Using-decorators.md:{% include content/tbd.html %}
        - need to look into the "review questions". also, it's not on the sidebar. 

- [ ] Review https://loopback.io/doc/en/lb4/Booting-an-Application.html

**Comment by bajtos** [comment]
@dhmlau I am proposing to treat this GH issue as a spike story to determine what work needs to be done and create follow-up issue to keep track of those changes needed. Can we include this story in our November milestone please?

**Comment by dhmlau** [comment]
Spike is done. We had: 
- review each docs page
- made minor fixes and enhancement 
- open github issues to track the work that involves more significant changes.
