### ISSUE TITLE
Monthly Milestone - December 2018 ⛄️ 🎄

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2084]
## December MIlestone
- Start the authentication & authorization story
- Help our users to get onboard with LB4
- Document how to make it easier to contribute
- Holidays! 🎄

### LoopBack 4
**Authentication & Authorization epic** #1035 
- [ ] 🚶Groundwork: Access tokens, login & logout #1997 

**Relation epic**
- [x] 🚶[Spike] How to do relation traversal: #1952 
- [x] 🚶[Relation] Supports HasOne relation #1422 

**Docs: make it easier to contribute**
- [x] How to report bugs and create reproducible example app: #1854
- [x] 🚶LB4 Documents need a cleanup pass #1908 

**Bug**
- [ ] Apidocs are not being built correctly #1299 

**Miscellaneous**
- [x] [Blog] Enabling users to support other content types #2083 
- [x] User experience on CLI, https://github.com/strongloop/loopback-next/issues/1842

### LoopBack 2.x, 3.x
- [x] `lb` freeze at "Enter name of the directory to contain the project" question https://github.com/strongloop/loopback-cli/issues/36
- [x] Update loopback-workspace from LB2 to LB3 https://github.com/strongloop/loopback-workspace/issues/498

### Stretch Goals

**Miscellaneous**
- [ ] Error: Unsupported type: geopoint  #1981 
- [ ] Using near filter in where query cause toEntity(model) bug #1419 
- [ ] 🚶Spike: How to write a LB3-like application in JavaScript #1978 
- [ ] 🚶Review: from Ruby to LoopBack, https://github.com/strongloop-internal/scrum-apex/issues/399

**Authentication & Authorization**
  - [ ] The First Scenario: Authenticated orders (a minimal authentication), https://github.com/strongloop/loopback-next/issues/1998
  - [x] Token based authentication in API Explorer, https://github.com/strongloop/loopback-next/issues/2027

**LoopBack as Express middleware**
- [ ] Tutorial/Blog to show how to mount LB app to Express/Koa as middleware, https://github.com/strongloop/loopback-next/issues/1982

**Docs**
- [ ] [Docs] Relation decorators page should be updated  #1910
- [x] How to contribute documentation: #1853 (SLIPPED)
- [x] [Docs] Update ways to contribute to LoopBack: #1228

**Feature and Spike**
- [ ] [Spike] Partial update (PATCH) over REST #2082 
- [ ] lb4 relations referential integrity #1718

**Comment by jannyHou** [comment]
We have an unfinished story from last month: 
- (5 story points) https://github.com/strongloop/loopback-next/issues/1952

---

Now the committed story points is **31** + **7(2 slipped stories from last month)** + **2 bugs(not estimated)**

Considering people will be on vacation(1-2 weeks) during Xmas, I am afraid the committed stories is more than we could finish. 

Shall we move some stories to the stretch goals? I would suggest move these 2:

- <spike> model constraint spike https://github.com/strongloop/loopback-next/issues/2082
- <unestimated bug> lb4 relations referential integrity #1718

cc @strongloop/sq-lb-apex @bajtos @raymondfeng thought?

**Comment by jannyHou** [comment]
@dhmlau Great. Then our committed story points would be 38 + unestimated bugs

**Comment by dhmlau** [comment]
Closing this as it's Jan now.  Moving outstanding items to [Jan milestone](https://github.com/strongloop/loopback-next/issues/2225).
