### ISSUE TITLE
Extension Examples, Tutorials, Docs

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-next#218]
- [x] #523 We need a brief architectural guide explaining high-level ideas to extension developers, few diagrams to visualize the concepts (Raymond).

- [x] #524 A blog post (stakeholders: Raymond, Kevin, Tetsuo,... owner: Tetsuo). Promote the issue created by Kevin (call for extensions).

- [x] #525 `loopback-next-hello-extension` - a github project people can `git clone` and start developing a new extension (TV).

**Comment by bajtos** [comment]
We need to make sure the authentication package can be used as a regular Component, also as a role model for component developers.

**Comment by dhmlau** [comment]
Per our latest discussion, what we need in this tutorial are:
- what is an extension
- why build extension

[Writing component wiki page ](https://github.com/strongloop/loopback-next/wiki/Writing-Components) could be a good starting point but it's not complete

**Comment by dhmlau** [comment]
@raymondfeng, assigning this to you as you'll be driving this. Thanks!

**Comment by bajtos** [comment]
- We need a brief architectural guide explaining high-level ideas to extension developers, few diagrams to visualize the concepts (Raymond).

- A blog post (stakeholders: Raymond, Kevin, Tetsuo,... owner: Tetsuo).

- `loopback-next-hello-extension` - a github project people can `git clone` and start developing a new extension (TV).

**Comment by bajtos** [comment]
The only remaining item is  #524, which is labelled as `p2`. I have relabelled this epic as `p2` too.
