### ISSUE TITLE
Monthly Milestone - January 2019 ❄️ 🎉 

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2225]
## January Milestone
- User adoption
- Authentication & Authorization
- Relations

### LoopBack 4
- [x] Authentication & Authorization epic #1035
  - [x] 🚶Groundwork: Access tokens, login & logout  #1997 
- [ ] User adoption
  - [ ] 🚶Spike: How to write a LB3-like application in JavaScript #1978 
  - [x] Promote LB4 in loopback.io site, https://github.com/strongloop/loopback.io/issues/786
  - [ ] 🚶[AppConnect] Review docs for connectors to identify migration roadblocks, https://github.com/strongloop-internal/scrum-apex/issues/400
- [x] Docs
  - [x] [Docs] Relation decorators page should be updated #1910
- [ ] Features & Spikes
  - [ ] [Spike] Partial update (PATCH) over REST #2082
- [ ] Bugs
  - [x] Apidocs are not being built correctly https://github.com/strongloop/loopback-next/issues/1299
  - [ ] 🚶Using near filter in where query cause toEntity(model) bug #1419 
- [x] Prep for [Toronto meetup](https://www.meetup.com/Toronto-Cloud-Integration-Meetup/events/257171001/) on Feb 5
   - [x] Meetup preparation - Presentation https://github.com/strongloop-internal/scrum-apex/issues/403
   - [x] Meetup Presentation - demo https://github.com/strongloop-internal/scrum-apex/issues/404

### Stretch Goals
- [ ] Relations: anything coming out from the Jan 17 meeting
  - [ ] Mongo fails to find user by id (hasMany relation not working) #2085 
  - [ ] [Spike] hasMany relation to same Entity fails #1682  
  - [ ] hasMany relation to same Entity fails #1571 
- [ ] Authentication & Authorization
  - [ ] The First Scenario: Authenticated orders (a minimal authentication) #1998
  - [ ] Spike: Token based authentication in API Explorer, #2027 
- [ ] User Adoption
  - [ ] Tutorial/Blog to show how to mount LB app to Express/Koa as middleware, #1982
  - [ ] 🚶Tutorial on how to build a LB4 app using plain JavaScript #1970 
- [ ] Migration
  - [ ] 🚶Spike on migration: Spike: drop LB3 model files into LB4 app #2224
- [ ] Error: Unsupported type: geopoint #1981

**Comment by b-admike** [comment]
Closing as done. Moved slipped stories to next milestone as appropriate, and blog is ready to be published.
