### ISSUE TITLE
[EPIC] Mount LB3 app in LB4

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2479]
Allow users migrating from LB3 to add their entire LB3 application into an LB4 project in such way that LB3 app's REST API is included in OpenAPI spec provided by the LB4 application and thus can be picked by LB4 clients including REST API Explorer.

See also the spike in #2301 and the PoC solution in #2224.

## Tasks 

_This is a snapshot from 2019-02-28. Use [ZenHub extension](https://www.zenhub.com/extension) or [ZenHub webapp](https://app.zenhub.com/workspaces/loopback-54ebffa9e8323184150c2125/issues/strongloop/loopback-next/2479) to access the always up-to-date list of stories contained in this epic._

- [x] Mount Express router with OpenAPI spec #2389 
- [x] Docs: request-handling pipeline #2390
- [x] Boot and mount LB3 app #2391
- [x] Example: mount LB3 app in LB4 #2392
- [x] Migration guide: mount LB3 in LB4 #2393
- ~~Spike: dynamically updated LB3 API (routes + spec) #2394~~ (Removed from the Epic, we can wait until there is user demand for this feature.)

**Comment by nabdelgadir** [comment]
Closing this epic as done.
