### ISSUE TITLE
Monthly Milestone - March 2019 ☀️🚗💐

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2516]
## March milestone
- Continue with Authentication & Authorization and migration story
- Review the extensibility PRs
- Triaging and review PRs from the community

### LoopBack 4 
- [x] Authentication #1035  
    - [x] Create abstraction for access token related operations in authentication module https://github.com/strongloop/loopback-next/issues/2435
    - [x] Create abstraction for login related operations in authentication module #2491

- [ ] Improve LB4 extensibility PRs
    - [x] feat(context): add support to watch context bindings, #2122
    - [ ]  🚶feat(context): support binding config and @inject.config, #2259
    - [x] [RFC] Greeter extension to illustrate extension point/extension pattern, #2249
    - [ ]  🚶feat(core): introduce basic life cycle support for LoopBack applications, #1928
    - [ ]  🚶feat(events): add basic async events support, #1972

- [x] Migration https://github.com/strongloop/loopback-next/issues/1849
    - [x] Mount Express router with OpenAPI spec https://github.com/strongloop/loopback-next/issues/2389
- [x] Bugs
     - [x] Explore the way to resolve inclusion property #2152 
     - [x] Partial update (PATCH) over REST #2082

- [x] Miscellaneous
    - [x] APIConnect 5.0.8.6 toolkit and collective testing (Deferred from Feb) https://github.com/strongloop-internal/scrum-apex/issues/405

#### Stretch goals
- [ ] Authentication
    - [ ] Add abstraction for authentication strategy #2466
    - [ ] Refactor the authentication action to be a common one #2467
- [ ] Bugs
   - [ ] Mongo fails to find user by id (hasMany relation not working) #2085
- [ ] Migration
    - [ ] Docs: request-handling pipeline https://github.com/strongloop/loopback-next/issues/2390
- [ ] JS Spike
  - [x] blog post on our findings and next step  https://github.com/strongloop/loopback-next/issues/2605
- [ ] Docs
    - [x] [Docs] Calling other APIs Page #1766
    - [ ] [Docs] "Testing your application" page contains beta release information #2101
    - [ ] [Docs] Update WIP section in Sequence page #2100
- [x] Miscellaneous
    - [x] Add a section in Resource page for our presentation videos, https://github.com/strongloop/v4.loopback.io/issues/61
    - [x] Add test  for - hasMany relation to same Entity fails #1571

### LoopBack 3
- [x] property name with `type`  is not working correctly with loopback complex model, https://github.com/strongloop/loopback/issues/4131
- [ ]  🚶Support for `Array of Array of Json` Object in model properties, https://github.com/strongloop/loopback/issues/4132

**Comment by ElHupeke** [comment]
Please have a look at Fireloop realtime integration. (https://github.com/mean-expert-official/fireloop.io) Missing this realtime functionality in LB4. In my case a must have :-)

**Comment by dhmlau** [comment]
@hacksparrow , at this point, I don't think it's a good idea to add the follow-up tasks for the JS spike in the March milestone, so I've removed the following from the list.  But I'd like to include the blog post that you're working on as part of the milestone.  Do you have any ticket created?  If so, could you please update the original description with the link?  Thanks.


```
    - [ ] Port the `examples/todo` app to JavaScript https://github.com/strongloop/loopback-next/issues/2501
    - [ ] Create Route in JSLB4 https://github.com/strongloop/loopback-next/issues/2474
    - [ ] From datasource config to DataSource instance with no custom classes https://github.com/strongloop/loopback-next/issues/2557 
```

**Comment by dhmlau** [comment]
@ElHupeke, for the realtime integration, could you please take a look at https://github.com/strongloop/loopback-next/issues/119 and continue the discussion over there?  Thanks!

**Comment by jannyHou** [comment]
Closing.
