### ISSUE TITLE
Enable TypeScript Project References

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2609]
At the moment, our monorepo is configured in a hacky way to allow TypeScript to build individual packages independently but still allow the TypeScript Language Service run by VSCode to treat the monorepo as one large project.

Let's abandon our non-standard setup and leverage TypeScript's [Project References](https://www.typescriptlang.org/docs/handbook/project-references.html) instead.

Work done so far:
- [x] build: drop multiple dist targets, always use es2017 #1803
- [x] refactor: let TypeScript do resource copying #1824
- [x] move test files to `src/__tests__` #2283 #2316 #2330 #2339

Work remaining:

- [ ] 🚶  remove top-level `index.*` files and use `main` & `types` entries in `package.json` instead #5440 ~~#2613~~ 
- [x]  chore: add script to build typescript project references #5155 ~~#1636~~
- [x] 🚶update example projects and CLI templates (if needed) #5204

Nice to have ~~implement it or create follow-up stories:~~
- Watch mode
- [x] Incremental builds - already done by #2928
- Incremental builds on Travis CI and AppVeyor - cache intermediate files between CI runs
  - Travis CI docs: https://docs.travis-ci.com/user/caching/
  - AppVeyor docs: https://www.appveyor.com/docs/build-cache/
