### ISSUE TITLE
Add navigational properties to examples/todo-list

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#2633]
Update `examples/todo-list` to leverage recently added features moving us closer to full inclusion of related models.

See the spike #2592 for more details.

## Acceptance criteria

- [x] Define `{Model}Relations` interfaces and `{Model}WithRelations` types

- [x] Update `{Model}Repository` implementations to use these new interfaces

- [x] Update repositories to include related models: overwrite `find` and `findById` methods, add a hard-coded retrieval of related models. This part depends on https://github.com/strongloop/loopback-next/issues/2632 

  Include a comment explaining that the example implementation is temporary and add a link to the GitHub issue tracking the work needed to implement production-grade inclusion resolver. 

- [x] Add test coverage at repository level (integration tests)

- [x] Update response schemas for controller methods `find` and `findById` to leverage `getModelSchemaRef` and `includeRelations`. This part depends on https://github.com/strongloop/loopback-next/issues/2631 and https://github.com/strongloop/loopback-next/issues/2630

- [x] Add acceptance-level tests to verify inclusion of related models via REST API

- [x] Update [Todo List Tutorial](https://loopback.io/doc/en/lb4/todo-list-tutorial.html)
