### ISSUE TITLE
Monthly Milestone - April 2019 🌿🐰☔️

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2669]
## April milestone
- Model relation - referential integrity
- Migration
- Review and triaging including the community PRs

### LoopBack 4
- [x] Authentication #1035 
   - [x] Add abstraction for authentication strategy, https://github.com/strongloop/loopback-next/issues/2466
- [x] Migration- Mount LB3 app in LB4, https://github.com/strongloop/loopback-next/issues/2479
   - [x] Docs: request-handling pipeline #2390.
   - [x] Boot and mount LB3 app #2391
- [x] Model Relations - Referential integrity
   - [x] Spike: declarative definition of FOREIGN KEY and UNIQUE constraints https://github.com/strongloop/loopback-next/issues/2606
- [x] Model Relations - Inclusion of related models https://github.com/strongloop/loopback-next/issues/1352
   - [x] Fix repository-json-schema to handle circular references #2628
- [x] Fix CI
   - [x] Fix CI for loopback-connector-mongodb: https://github.com/strongloop/loopback-connector-mongodb/issues/503
   - [x] Fix CI for loopback-connector-couchdb2: https://github.com/strongloop/loopback-connector-couchdb2/issues/60
- [ ] Review PRs
   - [ ] Extensibility PRs
      - [x] feat(core): introduce basic life cycle support for LoopBack applications, #1928 
      - [ ] feat(context): support binding config and @inject.config, #2259
      - [ ] ~feat(events): add basic async events support, #1972~ DEFERRED
   - [ ] Community PRs
      - [ ] feat(cli): add lb4 relation command #2426 
      - [x] Model discovery: https://github.com/strongloop/loopback-next/pull/2245

### Stretch goal
- [ ] Model Relations - Referential integrity
   - [x] Document hasMany/belongsTo/hasOne limitations for NoSQL databases https://github.com/strongloop/loopback-next/issues/2340
- [ ] Authentication
   - [ ] 🚶‍♂️Refactor the authentication action to be a common one, https://github.com/strongloop/loopback-next/issues/2467
   - [ ] 🚶‍♂️Extension point for registering the non-passport based authentication strategies, https://github.com/strongloop/loopback-next/issues/2312
- [ ] Bugs
   - [ ] Mongo fails to find user by id (hasMany relation not working) #2085 
- [ ] Migration
    - [ ] 🚶‍♂️Example: mount LB3 app in LB4 #2392
    - [x] Review docs for connectors to identify migration roadblocks https://github.com/strongloop-internal/scrum-apex/issues/400
- [ ] Unified web experience
    - [ ] Spike: Explore keeping the existing doc generation mechanism in LB4 site, https://github.com/strongloop/v4.loopback.io/issues/65
- [ ] Model Relations - Inclusion of related models https://github.com/strongloop/loopback-next/issues/1352
    - [ ] Allow controllers to provide definitions of models referenced in operation spec #2629 
    - [ ] Modify Repository find* methods to include navigational properties #2632
- [ ] Docs
    - [ ] [Docs] "Testing your application" page contains beta release information #2101
    - [ ] [Docs] Update WIP section in Sequence page #2100
- [ ] Reviews of community PRs on connectors
    - [x] Remove port when using mongodb+srv, https://github.com/strongloop/loopback-connector-mongodb/pull/497
    - [ ] Feature add foreign key on update on delete trigger config, https://github.com/strongloop/loopback-connector-mysql/pull/370
- [ ] Review PRs
   - [x] feat(context): improve @inject.setter and add @inject.binding #2657
   - [ ] feat(context): add support for method interceptors #2687
   - [x] fix(cli): improve openapi code generation for naming and typing #2722
   - [x] feat(rest): allow `-` to be used for path template variable names #2724
