### ISSUE TITLE
[Roadmap] 🚀2Q2019 🚀

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2692]
_This is a high-level issue keeping track of deliverables in the next 90 days.
Please note that this is our plan for the roadmap and it is subject to change._

## Overview
- Help out adopters, both new or existing LB users, and grow the contributor community
- Focus on feature parity gaps and LB3-to-LB4 migration

### Migration  https://github.com/strongloop/loopback-next/issues/1849
- [x] [EPIC] Mount LB3 app in LB4, https://github.com/strongloop/loopback-next/issues/2479
- [ ] [EPIC] Enable migration of AppConnect to LB4 https://github.com/strongloop-internal/scrum-apex/issues/396  _(Use this to validate our migration story)_

### Authentication  https://github.com/strongloop/loopback-next/issues/1035
- [x] Create extension points and adapter for passport strategies
  - [x] Extension point for registering the authentication strategies https://github.com/strongloop/loopback-next/issues/2312
  - [x] Creating adapter for the plugged in passport strategies, https://github.com/strongloop/loopback-next/issues/2311
- [x] Reference implementation of JWT authentication in example-shopping app. 
- [x] Docs: How to build your own authentication strategies - target for auth strategy developers.

### Model Relation
- [ ] [EPIC] Include related models https://github.com/strongloop/loopback-next/issues/1352.
- [ ] [EPIC] FK and UNIQUE constraints (Strong relation with referential integrity) https://github.com/strongloop/loopback-next/issues/2331.
  - [x] Document hasMany/belongsTo/hasOne limitations for NoSQL databases #2340 
  - [x] Spike: Declarative definition of FOREIGN KEY and UNIQUE constraints #2606
- [x] Document levels of referential integrity we support for different databases, explain how to configure database schemas to enable referential integrity when database schema is not created by LB 
  - [x] Document hasMany/belongsTo/hasOne limitations for NoSQL databases https://github.com/strongloop/loopback-next/issues/2340

### Authorization https://github.com/strongloop/loopback-next/issues/538
- [x] Spike on how to add support https://github.com/strongloop/loopback-next/issues/2718
- [x] Implementation on minimal infrastructure - stretch goal

### Declarative support  https://github.com/strongloop/loopback-next/issues/565
- [ ] API Creation with just models - without Repository and datasource - streamline API Creation by convention #2036

### Internal tooling/CI
- [x] CI failure in connector repos: https://github.com/strongloop-internal/scrum-apex/issues/381
- [ ] Test connectors with juggler@4 (LB4)
- [x] Move from TSLINT to ESLINT with TS plugins https://github.com/strongloop/loopback-next/issues/2608

### Transaction support 
- [x] docs: explain to users how to open a transaction and pass the txn token/handles around in options. https://github.com/strongloop/loopback-next/issues/2614

### Architectural Improvements
- [x] App life-cycle observers https://github.com/strongloop/loopback-next/issues/1039

### Unified Web experience - phase 2 https://github.com/strongloop/v4.loopback.io/issues/64
- [x] Spike: Explore keeping the existing doc generation mechanism in LB4 site https://github.com/strongloop/v4.loopback.io/issues/65
