### ISSUE TITLE
Monthly Milestone - May 2019 🌷🐝 🍄

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2818]
## May milestone
- Finish majority of the task in Authentication epic
- CI fixes and infrastructure

### Yak Shaving
  - [x] Mark LB 2.x as EOL https://github.com/strongloop/loopback/issues/4180
  - [ ] 🚶‍♂Explore how to roll out experimental features, https://github.com/strongloop/loopback-next/issues/2676

### LoopBack 4
- [x] CI fixes 
  - [x] cloudant connector https://github.com/strongloop/loopback-connector-cloudant/issues/201
  - [x] mongodb connector https://github.com/strongloop/loopback-connector-mongodb/issues/509
  - [x] REST connector https://github.com/strongloop/loopback-connector-rest/issues/133
- [x] CI infrastructure
  - [x] Spike: test both juggler version 3.x and 4.x with all connectors https://github.com/strongloop-internal/scrum-apex/issues/416
  - [x] Spike: Create monorepo for juggler and connectors https://github.com/strongloop/loopback-next/issues/2775
- [x] Authentication #1035 
  - [x] Refactor the authentication action to be a common one, #2467
  - [x] Extension point for registering the non-passport based authentication strategies, #2312 
- [ ] Bugs
  - [ ] 🚶‍♂Mongo fails to find user by id (hasMany relation not working) #2085
- [ ] Docs
  - [x] [Docs] "Testing your application" page contains beta release information #2101
  - [ ] 🚶‍♂[Docs] Update WIP section in Sequence page #2100
- [x] LB3 migration
  - [x] Example: mount LB3 app in LB4 #2392
- [x] Review PRs
  - [x] Community PR:  feat(cli): add lb4 relation command #2426
  - [x] feat(context): support binding config and @inject.config, #2259
  - [x] feat(context): add support for method interceptors #2687
  - [x] WebSocket support: https://github.com/strongloop/loopback-next/pull/2648

### Stretch Goals
- [ ] Authentication 
  - [x] Refactor shopping app to use the updated authentication package  strongloop/loopback4-example-shopping#79
  - [ ] Creating adapter for the plugged in passport strategies #2311
- [ ] ~Unified web experience~   Out of scope for Q2
  - [ ] ~Spike: Explore keeping the existing doc generation mechanism in LB4 site, strongloop/v4.loopback.io#65~
- [ ] Model Relations - Inclusion of related models #1352 
  - [x] Allow controllers to provide definitions of models referenced in operation spec #2629  
  - [ ] 🚶‍♂Modify Repository find* methods to include navigational properties #2632

**Comment by b-admike** [comment]
Closing as done.
