### ISSUE TITLE
[Epic] MVP: authentication extension points

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#2892]
## Description / Steps to reproduce / Feature proposal
Originated from https://github.com/strongloop/loopback-next/issues/1035. 
Creating a new epic to separate the authentication and authorization epic. 

Cross-posting the acceptance criteria from https://github.com/strongloop/loopback-next/issues/1035#issuecomment-487639092: 

- [x] create the authentication strategy interface #2466
- [x] make auth action in /authentication package to use interface created in 1/. #2467
- [x] Refactor example-shopping app to use the auth action in 2/ strongloop/loopback4-example-shopping#79
- [ ] Test if existing adapter works with passport strategies and interface. #2311
- [x] How to register auth strategies #2312
- [ ] Write blogs/docs about how one can register auth strategies #2725

## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by jannyHou** [comment]
@dhmlau Thank you it captures everything I am aware of.

**Comment by dhmlau** [comment]
Closing as done! 🎉
