### ISSUE TITLE
Monthly Milestone - Jun 2019 🌞🌺⛳️

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3035]
## June milestone
- Finish Q2 release!

### Goals
- [x] Inclusion of related models https://github.com/strongloop/loopback-next/issues/1352
  - [x] Add navigational properties to examples/todo-list https://github.com/strongloop/loopback-next/issues/2633
  - [x] Enhance `getJsonSchema` to describe navigational properties https://github.com/strongloop/loopback-next/issues/2630 [community contribution]

- [x] Authentication https://github.com/strongloop/loopback-next/issues/2892.
  - [x] Creating adapter for the plugged in passport strategies https://github.com/strongloop/loopback-next/issues/2311
  - [x] update the packages/authentication/README.md to showcase new authentication architecture, https://github.com/strongloop/loopback-next/issues/2940

- [x] Mount LB3 app in LB4 https://github.com/strongloop/loopback-next/issues/2479
  - [x] Migration guide: mount LB3 in LB4  https://github.com/strongloop/loopback-next/issues/2393

- [ ] Make sure docs is up-to-date https://github.com/strongloop/loopback-next/issues/1951
  - [ ] 🚶‍♂Add documentation for this example https://github.com/strongloop/loopback4-example-shopping/issues/69

- [x] Authorization  https://github.com/strongloop/loopback-next/issues/538
  - [x] [Spike] Investigate the minimal infrastructure we need to support authorization https://github.com/strongloop/loopback-next/issues/2718

- [ ] Miscellaneous
  - [x] Wrong Model name in Repository/Controller by CLI when a Model name https://github.com/strongloop/loopback-next/issues/2644
  - [ ] 🚶‍♂ Docs: How to create a transaction and pass it around through various repo CRUD operations https://github.com/strongloop/loopback-next/issues/2614
  - [x] Assess whether APIC collectives work with Node.js 10, https://github.com/strongloop-internal/scrum-apex/issues/420

- [x] PRs to review
  - [x] feat(cli): add `lb4 interceptor` to generate interceptors and a booter to load interceptors https://github.com/strongloop/loopback-next/pull/2907
  - [x] feat(rest): allows validation (AJV) options to be configured via RequestBodyParserOptions https://github.com/strongloop/loopback-next/pull/2992

### Stretch Goals
- [x] Infrastructure
  - [x] Run shared tests from both v3 and v4 of juggler (cloudant) https://github.com/strongloop/loopback-connector-cloudant/issues/205
  - [x] Switch from tslint to eslint https://github.com/strongloop/loopback-next/issues/2608
  - [x] Release `@loopback/build` version `2.0.0` https://github.com/strongloop/loopback-next/issues/3061

- [ ] Inclusion of related models https://github.com/strongloop/loopback-next/issues/1352. 
  - [ ] 🚶‍♂Spike: Resolver for inclusion of related models https://github.com/strongloop/loopback-next/issues/2634

- [x] Authentication https://github.com/strongloop/loopback-next/issues/2892. 
  - [x] [Blog] How to register authentication strategies https://github.com/strongloop/loopback-next/issues/2725

- [ ] PRs to review
  - [x] https://github.com/strongloop/loopback-next/pull/2908
  - [ ] https://github.com/strongloop/loopback-next/pull/2927

- [ ] p2 items
  - [ ] [Inclusion of related models] Spike: simplify requestBody annotation with schema options https://github.com/strongloop/loopback-next/issues/2654
  - [ ] CI failure clean up https://github.com/strongloop-internal/scrum-apex/issues/381
    - [ ] ~[Spike] Fix CI Failures (dashdb)  https://github.com/strongloop/loopback-connector-dashdb/issues/76~ Out of scope for Q2 
    - [ ] ~Fix CI failures (db2) https://github.com/strongloop/loopback-connector-db2/issues/130~ Out of scope for Q2 
- [ ] Authorization  https://github.com/strongloop/loopback-next/issues/538. 
  - [ ] Create a common layer for authentication & authorization component https://github.com/strongloop/loopback-next/issues/2900
