### ISSUE TITLE
[Epic] Test/Enable Node.js 12 support for connectors

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3072]
Through PR https://github.com/strongloop/loopback-datasource-juggler/pull/1728 and https://github.com/strongloop/loopback-datasource-juggler/pull/1729, `loopback-datasource-juggler` now supports Node.js 12.  The next step is to test and add support for Node.js 12.x for the connectors. 

### Acceptance Criteria
For the following connectors, test locally on Node.js 12 and see if all tests passed.  
- If yes, add Node.js 12 to CI 
- If not, try to fix it for simple fixes.  If you don't think you can fix it in a day, open a new issue to keep track of it.

Here is the list of connectors:

_SQL connectors:_ https://github.com/strongloop/loopback-next/issues/3110
- [x] loopback-connector
- [x] loopback-connector-mysql
- [x] loopback-connector-postgresql
- [x] loopback-connector-mssql
- [x] loopback-connector-oracle
- [ ] ~loopback-connector-db2~ (doesn't work with node 12 yet)

_noSQL connectors:_ https://github.com/strongloop/loopback-next/issues/3111
- [x] loopback-connector-mongodb
- [x] loopback-connector-couchdb2
- [x] loopback-connector-cloudant
- [x] loopback-connector-cassandra

_service connectors:_ https://github.com/strongloop/loopback-next/issues/3112
- [x] loopback-connector-remote
- [x] loopback-connector-rest
- [x] loopback-connector-soap
- [ ] ~loopback-connector-swagger~ deprecated
- [x] loopback-connector-jsonrpc
- [x] loopback-connector-openapi

_currently with CI issues:_
- [x] loopback-connector-kv-redis
- [x] loopback-connector-grpc
- [ ] loopback-connector-mqlight
- [ ] ~loopback-connector-dashdb~ (doesn't work with node 12 yet)
- [ ] loopback-connector-kv-extreme-scale

_not sure if we need to enable Node.js 12_
- [ ] loopback-connector-db2iseries (we don't have an instance to test??)
- [ ] loopback-connector-informix (we don't have an instance to test??)
- [ ] loopback-connector-db2z (we don't have an instance to test??)
- [ ] loopback-connector-zosconnectee (??)

_I'm taking the list from https://github.com/strongloop?utf8=%E2%9C%93&q=loopback-connector&type=&language=_

**Comment by dhmlau** [comment]
We've enabled and tested the most commonly used connectors with Node.js 12.  For the rest, we'll enable it later.  Moving to Q4.

**Comment by dhmlau** [comment]
We have finished the requirement for Q4, i.e. enable and test Node.js 12 for:
- loopback-connector-kv-redis
- loopback-connector-grpc

Moving the `2019Q4` label.

**Comment by dhmlau** [comment]
Consider it done.  The rest are not very active repos.
