### ISSUE TITLE
Application.component() : load a component with controllers and mvp (meta value providers)

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#319]
Updated as per discussions: (for details look below in this thread)

- [x]  Create an interface for Providers
- [x]  Method Binding.prototype.toProvider() to bind a provider
- [ ]  Method Application.component to load a component in the container/context

**Comment by ritch** [comment]
Basic impl:

```ts
class Application {
  component(component : Component) {
    for (let [name, provider] of Object.entries(component.providers)) {
      this.bind(name, provider)
    }
    for (let [name, controller] of Object.entries(component.providers)) {
      this.controller(name, provider)
    }
  }
}
```

**Comment by ritch** [comment]
Here's some tests that describe `Provider` (also see loopback-next-sandbox)

```
describe('Provider', () => {
  let provider: Provider;
  beforeEach(givenProvider);

  describe('key', () => {
    it('identifies the provider', () => {
      expect(provider.key).to.equal('MY_KEY');
    });
  });

  describe('value()', () => {
    it('returns the value synchronously', () => {
      expect(provider.value()).to.equal('hello world');
    });
  });

  function givenProvider() {
    provider = new MyProvider('hello');
  }
});

class MyProvider implements Provider {
  constructor(private _msg : string) {}
  static key = 'MY_KEY';
  value() {
    return this._msg + ' world';
  }
}
```

**Comment by ritch** [comment]
We would also need `Binding.prototype.toProvider(provider: Provider)`

**Comment by bajtos** [comment]
As I explained in https://github.com/strongloop/loopback-next/pull/323#pullrequestreview-41417945, I think the Provider class needs to support at least two semantics: "bind to value" (as proposed here) but also "bind to class constructor" (not supported). Considering that the `Binding` class already knows the key and how to provide the bound value, I am proposing that components should be exporting binding instances directly. See my comment in the pull request for more details.

**Comment by deepakrkris** [comment]
@bajtos your comments suggest the need of an `InstanceProvider` which could provide instances of a class. This way we could give support for singleton instances and per request instances
@raymondfeng @ritch @superkhau

**Comment by deepakrkris** [comment]
I am suggesting a few changes to the design of the ValueProvider Interface as below
```
export abstract class ValueProvider {
  constructor(readonly metadata: ProviderMeta) {}
  abstract value(): BoundValue | Promise<BoundValue>;
}
```
- [X]  given that static variables are not supported in interfaces change ValueProvider to an abstract class
- [X]  inject the provider key via the ValueProvider constructor as readonly
- [X]  provide the constructor arguments as a ProviderMeta class instance which has key as a readonly property.

**Comment by deepakrkris** [comment]
per conversation with @raymondfeng , we dont need a `static key ` property in the provider. that would stand different from the toClass() implementation. 
`ctx.bind('mykey').toProvider(provider)`
`ctx.bind('mykey').toClass(class)`

I suggest the following decorator approach 
```
@provider('mykey', options)
export class SampleProvider Implements ValueProvider {
  constructor(@inject private msg: string) {}
  value(): BoundValue | Promise<BoundValue> {
     return this.msg.toUpperCase();
  }
}
ctx.register(SampleProvider);
```

@ritch @raymondfeng @superkhau @bajtos

**Comment by bajtos** [comment]
Here are the three use cases I think we need to support by our Provider API:


 1. As a component, I want to export a provider/binding that binds "log" to a constant value "msg => console.log(msg)".

    Here is how I would achieve that inside loopback core:

    ```ts
    ctx.bind('log').to(msg => console.log(msg));
    ```

 2. As a component, I want to export a provider/binding that binds "now" to a value computed by a factory function "Date.now". 

    Here is how I would achieve that inside loopback core:

    ```ts
    ctx.bind('now').toDynamicValue(() => Date.now());
    ```

 3. As a component, I want to export a provider/binding that binds "ProductController" to a value that's created by calling "ProductController" and injecting any constructor or property dependencies. At the same time, I don't want to care about these dependencies in the code that's registering the binding, I want the IoC framework to take care of that.

    Here is how I would achieve that inside loopback core:

    ```ts
    class ProductController {
      @inject('log')
      public log;

      constructor(@inject('now') public created) {}
      }

      greet() {
        this.log(`Hello from a controller instance created at ${this.created}`);
      }
    }

    ctx.bind('ProductController').toClass(ProductController);
    ```

I am proposing to treat those three items above as a base for our acceptance criteria.

@deepakrkris Could you please describe how each of the use cases described above can be implemented in the design you have proposed?

IMO, it would be great if the API for registering bindings by code that has access to the context object (inside loopback core, but also in user applications) was as close as possible to the new API for components.

**Comment by raymondfeng** [comment]
@bajtos Good summary. I would like to add one more use case.

1. As a component, I want to export a provider/binding that binds "hello-with-timestamp" to a value that depends on `now` binding.

Here are a few ways I can achieve: 
```js
ctx.bind('hello-with-timestamp').toDynamicValue((ctx) => ctx.getSync('now') + ': Hello');
```
Or
```js
class HelloWithTSProvider {
  constructor(private @inject('now') now: Date) {}
  value():string {
    return this.now + ': Hello';
  }
}
ctx.bind('hello-with-timestamp').toProvider(HelloWithTSProvider);
```
Or
```js
class HelloWithTSProvider {
  static value(@inject('now') now: Date):string {
    return now + ': Hello';
  }
}
ctx.bind('hello-with-timestamp').toProvider(HelloWithTSProvider);
```

**Comment by deepakrkris** [comment]
as suggested by @bajtos 

the binding/provider implementation cannot reliably detect whether a function value is meant to be a value-to-be-returned, a getter function, or a class constructor that requires dependencies to be injected.

I agree with Raymond that the provider itself should not need to know its key, I think the same argument can be made for `Binding` class too.  Maybe its time to extract a small class out of `Binding`, something like the following:

```class ValueProvider
  readonly valueConstructor: string | undefined;

  constructor(public readonly getValue: (context) => BoundValue  | Promise<BoundValue>) {}
  
  static fromValue(value) {
    return new ValueProvider(() => value);
  }

  static fromFactory(factoryFn) {
    return new ValueProvider(() => factoryFn());
  }

  static fromClass(classCtor) {
    const result = new ValueProvider(ctx => instantiateClass(ctor, ctx));
    result.valueConstructor = classCtor;
    return result;
  }
}
```

While we are speaking about this, let's discuss the "locked" and "tag" properties - how can components signal which exported bindings should be locked and how they should be tagged?

**Comment by deepakrkris** [comment]
following comments were suggested by @bajtos

 I agree with Raymond that the provider itself should not need to know its key, I think the same argument can be made for `Binding` class too.  Maybe its time to extract a small class out of `Binding`, something like the following:

( edited for clarity by Deepak)  @bajtos  please check
```
// Provider class
class ValueProvider {
  readonly valueConstructor: string | undefined;
  constructor(public readonly getValue: (context) => BoundValue  | Promise<BoundValue>) {}
}
// Binding class
class Binding {
 .....
  static fromValue(value) {
    return new ValueProvider(() => value);
  }

  static fromFactory(factoryFn) {
    return new ValueProvider(() => factoryFn());
  }

  static fromClass(classCtor) {
    const result = new ValueProvider(ctx => instantiateClass(ctor, ctx));
    result.valueConstructor = classCtor;
    return result;
  }
}
```

**Comment by deepakrkris** [comment]
@bajtos  : 
While we are speaking about this, let's discuss the "locked" and "tag" properties - how can components signal which exported bindings should be locked and how they should be tagged?

**Comment by bajtos** [comment]
> As a component, I want to export a provider/binding that binds "hello-with-timestamp" to a value that depends on now binding.

@raymondfeng yes, that's a good one, it's something we need to implement in `Context` too.

I would personally change your first example a little bit:

```ts
ctx.bind('hello-with-timestamp').toDynamicValue('now', (now) => ctx.getSync('now') + ': Hello');
```

I am thinking about the following signature(s) of `toDynamicFunction`:

```ts
toDynamicValue(factoryFn: () => BoundValue | Promise<BoundValue>): this;
toDynamicValue<A1>(inject1: string, factoryFn: (a1: A1) => BoundValue | Promise<BoundValue>): this;
toDynamicValue<A1, A2>(inject1: string, inject2: string, factoryFn: (a1: A1, a2: A2) => BoundValue | Promise<BoundValue>): this;
// ...
```

My proposed API has one important feature: the compiler can verify that the number of injected values matches the number of factory-function arguments.

```ts
// ok
.toDynamicValue('now', now => `${now}: Hello`)
// error
.toDynamicValue('now', () => `${now}: Hello`)
.toDynamicValue('now', 'logError', (now) => `${now}: Hello`)
```

I have a POC implementation of that proposal here: https://github.com/strongloop/loopback-next/commit/28872c01ac9259a5e92221892e5815eb1a217b97#diff-5002f85388fd058d3115d43d66ee1286R92

**Comment by ritch** [comment]
The original intention of `Provider` was to implement this feature:

```js
function getSomeValue(@inject('foo') foo) {
  // foo is resolved only when this function is called
}
```

This syntax isn't possible since you can't decorate a `function`. So the minimal `Provider` interface was introduced, but we lost this main use case.

```ts
class FooProvider {
  constructor(public @inject('foo') foo) {}
  value() {
    // foo should not be resolved until this function is called
    // (in the current impl it is)
  }
}
```

Once this was introduced, we piggy backed on the `Provider` concept to easily list / name / bind providers from a component: https://github.com/strongloop/loopback-next-sandbox/blob/master/ts/src/components/todo/index.ts#L9

The point is we should just solve for these two use cases:

 - `foo` should only be injected / resolved on demand - when that is required by a `Provider`
 - it should be easy to create / name / import / bind many `Providers` in a component

**Comment by raymondfeng** [comment]
@bajtos Your proposal is similar as https://github.com/amdjs/amdjs-api/wiki/AMD#using-require-and-exports. I don't think we need to introduce another flavor of dependency injection though. I would rather stick with `@inject` and use a class as the wrapper.

**Comment by bajtos** [comment]
> Your proposal is similar as https://github.com/amdjs/amdjs-api/wiki/AMD#using-require-and-exports.

Yes, it's similar to AMD and also to AngularJS 1.x

> I don't think we need to introduce another flavor of dependency injection though. I would rather stick with @inject and use a class as the wrapper.

I am concerned that we are forcing people to use classes in places where a good old function would be enough. Compare how much code is needed by the class-based approach compared to the function-based I am advocating for:

```ts
// class-based
class HelloWithTSProvider {
  constructor(private @inject('now') now: Date) {}
  value():string {
    return this.now + ': Hello';
  }
}
ctx.bind('hello-with-timestamp').toProvider(HelloWithTSProvider);

// function-based
ctx.bind('hello-with-timestamp')
  .toDynamicValue('now', now => `${now}: Hello`);
```

At micro-optimization level, the class-based approach allocates an extra object instance, which can affect the performance.

I personally prefer to support both flavours.

> This syntax isn't possible since you can't decorate a function. So the minimal Provider interface was introduced, but we lost this main use case.

Thanks @ritch for a reminder of the original goal, it's easy to loose it in design discussions. I don't have a strong opinion on how to support the provider use case you have described. 

In my proposal, I am trying to address the needs I found while working on `Sequence` implementation. In particular, how to move the definition of `findRoute` and `invokeMethod` bindings to application-level context, when the bound function needs to access request-specific values - see [packages/core/src/http-handler.ts#L54-L82](https://github.com/strongloop/loopback-next/blob/67841d32131b896e8b09cb0b4e171f8ca067bab3/packages/core/src/http-handler.ts#L54-L82)

**Comment by ritch** [comment]
```js
ctx.bind('hello-with-timestamp')
  .toDynamicValue('now', now => `${now}: Hello`);
```

I'd prefer to focus on this syntax and support the JIT resolution I mentioned above using this metadata. 

> In my proposal, I am trying to address the needs I found while working on Sequence implementation. In particular, how to move the definition of findRoute and invokeMethod bindings to application-level context

I have an approach that should allow binding `findRoute` at the app level context:
https://github.com/strongloop/loopback-next/issues/336

I'll update it with the new `toDynamicValue` syntax proposed here.
