### ISSUE TITLE
Monthly Milestone - Jul 2019 🌴⚽️🍒

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3241]
## July Milestone
- Finish the items originally marked as stretch goals for Q2 release

### Goals
- [x] Documentation Improvement https://github.com/strongloop/loopback-next/issues/3240
  - [x] Documentation of loopback 4 Model is incorrect, https://github.com/strongloop/loopback-next/issues/2133
  - [x] Add "Connectors Reference" docs pages to LB4 docs, https://github.com/strongloop/loopback-next/issues/2598

- [x] Internal Tooling 
  - [x]  [Spike] Fix CI Failures (dashdb) https://github.com/strongloop/loopback-connector-dashdb/issues/76
  - [x] Fix CI failures (db2) https://github.com/strongloop/loopback-connector-db2/issues/130
  - [x] Run shared tests from both v3 and v4 of juggler https://github.com/strongloop/loopback-connector-mysql/issues/386
  - [x] Enable eslint for CLI package https://github.com/strongloop/loopback-next/issues/1851

- [ ] Inclusion of related models #1352
  - [ ] 🚶‍♂Spike: simplify requestBody annotation with schema options https://github.com/strongloop/loopback-next/issues/2654

- [ ] Bugs
  - [x] Using custom (underscored) keys for Relations : "Cannot read property 'target' of undefined"https://github.com/strongloop/loopback-next/issues/2169
  - [ ]  🚶‍♂throws MaxListenersExceededWarning  https://github.com/strongloop/loopback-next/issues/2198
  - [x] CLI issues: Generated app default Project name invalid if CWD name has hyphens + why not generate in CWD https://github.com/strongloop/loopback-next/issues/2092

- [ ] Miscellaneous
  - [x] Emit schema with all model properties optional https://github.com/strongloop/loopback-next/issues/2652
  - [x] Emit schema excluding certain model properties https://github.com/strongloop/loopback-next/issues/2653
  - [ ] Code review on loopback-connector-ibmi: https://github.com/strongloop-internal/scrum-apex/issues/415

## Stretch Goal
- [ ] Authentication
  - [ ] [Spike] Token based authentication in API Explorer, https://github.com/strongloop/loopback-next/issues/2027
- [ ] Authorization
  - [ ] PR: feat: add authorization component  https://github.com/strongloop/loopback-next/pull/1205
  - [ ] Create a common layer for authentication & authorization component
https://github.com/strongloop/loopback-next/issues/2900
- [ ] Internal Tooling
  - [ ] Spike: Investigate setting up Windows CI workflow for connectors - Azure Pipelines, https://github.com/strongloop/loopback-next/issues/3161
  - [x] [mssql] Run shared tests from both v3 and v4 of juggler https://github.com/strongloop/loopback-connector-mssql/issues/204
  - [x] [oracle] Run shared tests from both v3 and v4 of juggler https://github.com/strongloop/loopback-connector-oracle/issues/178

- [x] Bugs
  - [x] Migration error does not get caught, https://github.com/strongloop/loopback-next/issues/3044
  - [x] Multiple content types in requestBody problem, https://github.com/strongloop/loopback-next/issues/3234
