### ISSUE TITLE
Update `todo-list` example to use inclusion resolver

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3450]
Remove manually written "poor man's" resolvers, replace them with the real resolvers.

See also https://github.com/strongloop/loopback-next/pull/3387

## Acceptance criteria

Repositories to modify:
- [ ] [todo-list.repository.ts](https://github.com/strongloop/loopback-next/blob/master/examples/todo-list/src/repositories/todo-list.repository.ts)
- [ ] [todo.repository.ts](https://github.com/strongloop/loopback-next/blob/master/examples/todo-list/src/repositories/todo.repository.ts)
- [ ] [todo-list-image.repository.ts](https://github.com/strongloop/loopback-next/blob/master/examples/todo-list/src/repositories/todo-list-image.repository.ts)
