### ISSUE TITLE
Monthly Milestone - Aug 2019 🐟🔥🍤

### ISSUE THREAD

**Issue by agnes512** [strongloop/loopback-next#3482]
### Goals
- [x] Authentication
  - [x] [Create a common layer for authentication & authorization component](https://github.com/strongloop/loopback-next/issues/2900)
  - [x] [Update package.json and package-lock.json to remove passport references](https://github.com/strongloop/loopback4-example-shopping/issues/175)

- [x] Authorization
  - [x] PR: feat: add authorization component  https://github.com/strongloop/loopback-next/pull/1205

- [ ] Inclusion of related models. [Link](https://github.com/strongloop/loopback-next/issues/1352) 
  - [x] [Add `findByForeignKeys` helper](https://github.com/strongloop/loopback-next/issues/3443)
  - [x] [Introduce `InclusionResolver` concept](https://github.com/strongloop/loopback-next/issues/3445)
  - [x] [Include related models in `DefaultCrudRepository`](https://github.com/strongloop/loopback-next/issues/3446) 
  - [x] [Test relations against databases](https://github.com/strongloop/loopback-next/issues/3442)

- [ ] Declarative support [Link](https://github.com/strongloop/loopback-next/issues/2036)
  - [x]  [Extension: CrudRestController](https://github.com/strongloop/loopback-next/issues/2736) <-- do this one first, then spike.
  - [ ] Spike: [Booter for creating REST APIs from model files](https://github.com/strongloop/loopback-next/issues/2738)

- [x] Bug 
  - [x] [`lb4 relation` doesn't allow to add belongsTo & hasMany relation with the same 2 models](https://github.com/strongloop/loopback-next/issues/3186)
  - [x] [DefaultValueHandling to Reduce JSON Size](https://github.com/strongloop/loopback-connector-mongodb/issues/534)

- [ ] CI cleanup
  - [ ] 🚶[Fix CI issue with loopback-connector-oracle](https://github.com/strongloop/loopback-connector-oracle/issues/183)

- [x] Miscellaneous
  - [x] [Code review on loopback-connector-ibmi](https://github.com/strongloop-internal/scrum-apex/issues/415)
  - [x] [throws MaxListenersExceededWarning](https://github.com/strongloop/loopback-next/issues/2198)

### Stretch Goals

- [ ] Inclusion of related models
  - [ ] [Implement InclusionResolver for belongsTo relation](https://github.com/strongloop/loopback-next/issues/3448) 
  - [ ]  🚶[Implement InclusionResolver for hasMany relation](https://github.com/strongloop/loopback-next/issues/3447)
  - [ ] [Implement InclusionResolver for hasOne relation](https://github.com/strongloop/loopback-next/issues/3449)
- [ ] Juggler-Next
  - [ ] ~[Allow connectors to be implemented as ES6 classes](https://github.com/strongloop/loopback-datasource-juggler/issues/1758)~ Moved to Q4
  - [ ] ~[Allow connectors to use async/await](https://github.com/strongloop/loopback-datasource-juggler/issues/1659)~ Changed to be Q3 p2 item.  Need to work on Q3 p1 item first.
- [ ] Authentication
  - [ ] Spike: [Token based authentication in API Explorer](https://github.com/strongloop/loopback-next/issues/2027)
- [x] Documentation improvement
  - [x] [Add diagrams for "Key Concepts" page](https://github.com/strongloop/loopback-next/issues/3383)
