### ISSUE TITLE
Monthly Milestone - Sep 2019 🍇🍁🐛

### ISSUE THREAD

**Issue by agnes512** [strongloop/loopback-next#3653]
### Goals

Inclusion of related models
  - [x]  Implement `InclusionResolver` for hasMany relation https://github.com/strongloop/loopback-next/issues/3447
  - [x] Implement `InclusionResolver` for belongsTo relation https://github.com/strongloop/loopback-next/issues/3448 
  - [x]  Implement `InclusionResolver` for hasOne relation https://github.com/strongloop/loopback-next/issues/3449
  - [x] Add `keyFrom` to resolved relation metadata, https://github.com/strongloop/loopback-next/issues/3441

Authentication
  - [x] [Spike] Token based authentication in API Explorer https://github.com/strongloop/loopback-next/issues/2027
  - [x] [Spike] Make model `UserProfile` more flexible https://github.com/strongloop/loopback-next/issues/2246

Docs
  - [ ] 🚶`belongsTo()` not working in loopback4 - Cannot read property 'target' of undefined https://github.com/strongloop/loopback-next/issues/2639 -- SCOPE CHANGED. MOVED TO OCTOBER

Database Migration
  - [x] Migration of LoopBack 3 Models https://github.com/strongloop/loopback-next/issues/2825

Declarative support & Migration from LB3
  - [x] Import LB3 model JSON file to LB4 model class https://github.com/strongloop/loopback-next/issues/2480

Miscellaneous
  - [x] Spike: Booter for creating REST APIs from model files: https://github.com/strongloop/loopback-next/issues/2738
  - [x] Fix CI failures in Oracle DB connector : https://github.com/strongloop/loopback-connector-oracle/issues/183

Community PR review
  - [ ] `HasManyThrough` using `HasMany` https://github.com/strongloop/loopback-next/pull/2359

### Stretch Goals

Inclusion of related models 
  - [x]  Update `todo-list` example to use inclusion resolver https://github.com/strongloop/loopback-next/issues/3450

Docs
  - [ ] Add page for "Inside a LoopBack 4 application" https://github.com/strongloop/loopback-next/issues/3382
  - [x] Dev docs: explain how we work with GitHub issues and ZenHub https://github.com/strongloop/loopback-next/issues/1852
  - [ ] refactoring: customer credentials https://github.com/strongloop/loopback-next/issues/1996

Juggler-next
- [ ] Allow connectors to use async/await https://github.com/strongloop/loopback-datasource-juggler/issues/1659 -- COMMUNITY CONTRIBUTION.
