### ISSUE TITLE
Monthly Milestone - Oct 2019 🎃🌘🍂

### ISSUE THREAD

**Issue by agnes512** [strongloop/loopback-next#3801]
### Goals

_Inclusion of related models_
- [x] Add inclusion resolvers to `lb4 relation` CLI https://github.com/strongloop/loopback-next/issues/3451
- [x]  Blog post: announce Inclusion of related models https://github.com/strongloop/loopback-next/issues/3452
- [x] Run repository tests for PostgreSQL, https://github.com/strongloop/loopback-next/issues/3436

_Authentication_ 
- [x]  Enable the authorize button from swagger-ui in the shopping example with tutorial, https://github.com/strongloop/loopback-next/issues/3740

_Docs_
- [x] Add page for "Inside a LoopBack 4 application" https://github.com/strongloop/loopback-next/issues/3382

_Migration_
- [x]  Spike: Migration guide from LB3 - General runtime https://github.com/strongloop/loopback-next/issues/3718

_CASCON Workshop_
- [x] [Spike] CASCON Expo prep work, https://github.com/strongloop/loopback-next/issues/3693
- [x] [CASCON] Create demo app + hands on exercise instruction: https://github.com/strongloop/loopback-next/issues/3800
- [x] [CASCON] Workshop dry run https://github.com/strongloop/loopback-next/issues/3803
- [x] [CASCON] Prepare slides https://github.com/strongloop/loopback-next/issues/3802 

_Bug fixes / CI fixes_
- [x] Fix CI builds (Karma + PhantomJS), https://github.com/strongloop/loopback/issues/4252
- [x] PersisteModel's `updateAll` method crashes the server when invoked via the remote connector https://github.com/strongloop/loopback/issues/3717
- [x] Model discovery not working with Oracle connector & CDB instance https://github.com/strongloop/loopback-next/issues/3296  :warning: need estimate

_Cloudant: Support for Partitioned Databases_
- [x] [Spike] Add Support for Partitioned Databases, https://github.com/strongloop/loopback-connector-cloudant/issues/214
- [x] Update driver to nodejs/cloudant, https://github.com/strongloop/loopback-connector-cloudant/issues/215

### Stretch Goals
_Inclusion of related models_
- [ ] 🏃Run repository tests for Cloudant, https://github.com/strongloop/loopback-next/issues/3437

_Deployment_
- [ ] [Blog post] Show how to deploy a LB application in a cloud native environment https://github.com/strongloop/loopback-next/issues/3715

_Authentication_
- [ ] 🏃refactoring: customer credentials https://github.com/strongloop/loopback-next/issues/1996

_Authorization_ 
- [ ] 🏃Update the authorization tutorial, https://github.com/strongloop/loopback-next/issues/3694
- [ ] Apply authorization in the shopping example, https://github.com/strongloop/loopback-next/issues/3695

_From model definition to REST API with no custom repository/controller classes_
- [x] Improve `defineCrudRestController` to create a named controller class https://github.com/strongloop/loopback-next/issues/3732
- [x] Add `defineCrudRepositoryClass` - a helper to create a named repository class https://github.com/strongloop/loopback-next/issues/3733

_Cloudant: partitioned database support_
- [ ] Support creating partitioned index https://github.com/strongloop/loopback-connector-cloudant/issues/216

_Miscellaneous_
- [ ] Add loopback-connector-openapi and loopback-connector-grpc to be part of the available connectors https://github.com/strongloop/loopback-next/issues/3714
- [x] `belongsTo()` not working in loopback4 - Cannot read property 'target' of undefined https://github.com/strongloop/loopback-next/issues/2639

**Comment by dhmlau** [comment]
Closing as Oct has passed.
@emonddr , could you please make sure we have the outstanding tasks in this milestone moved to Nov? Thanks!
