### ISSUE TITLE
String type in the generated model class from lb4 discover not correct

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#3806]
Related to https://github.com/strongloop/loopback-next/issues/2953

It seems like some of the items mentioned in https://github.com/strongloop/loopback-next/issues/2953 wasn't fixed completely.

Runs the `lb4 discover` command and the generated code isn't exactly what we're looking for. 

## Steps to reproduce

1. Create a very simple table, e.g. 
```
  Table "public.customer"
  Column  | Type | Collation | Nullable | Default 
----------+------+-----------+----------+---------
 custid   | text |           | not null | 
 custname | text |           |          | 
```

This is my command on postgres: 
```
CREATE TABLE customer (custid text PRIMARY KEY, custname text);
```

2. Scaffold an app and create a datasource that connects to a database

3. Run:
```
npm run build
npm run migrate
```

## Current Behavior

```
@property({
    type: String,
    required: true,
    id: 1,
    postgresql: {"columnName":"custid","dataType":"text","dataLength":null,"dataPrecision":null,"dataScale":null,"nullable":"NO"},
  })
  custid: String;
```

## Expected Behavior

```
@property({
    type: string, <----- problem 1: lower case "string"
    required: true,
    id: 1,
    postgresql: {"columnName":"custid","dataType":"text","dataLength":null,"dataPrecision":null,"dataScale":null,"nullable":"NO"}, <--- problem 2: ideally it is formatted properly
  })
  custid: String;  <---- problem 3: lower case "string" 
```

See details in https://github.com/strongloop/loopback-next/issues/2953#issuecomment-495578669

## Acceptance Criteria
There are more details in https://github.com/strongloop/loopback-next/issues/3711 from @bajtos. 
- [x]  inside `@property`, change the type to be `string` instead of `String` (listed as problem 1 above) --> see #4143
- [x] as the type of the property, change the type to be `string` instead of `String` (listed as problem 3 above) --> see #4143
- [ ] Stretch goal: in the connector specific json inside `@property`, represent it as a TypeScript object --> see #4180

**Comment by bajtos** [comment]
See also #3711 that describes another aspect of this problem, one related to controllers & repositories.

**Comment by emonddr** [comment]
Double-check for other types as well.

**Comment by jannyHou** [comment]
My finding so far:

The model discover generator calls [discoverSingleModel](https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/discover/index.js#L196) to get model definitions, and the schema returned from [this function](https://github.com/strongloop/loopback-next/blob/master/packages/cli/lib/model-discoverer.js#L30) has primitive data type as camel case like `String`, instead of all lower case `string`
