### ISSUE TITLE
Final content for Thinking in LoopBack

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-next#393]
Only had a draft done during the previous sprint, the goal is to get some final content in https://github.com/strongloop/loopback-next/wiki/Thinking-in-LoopBack

 - [x] #546 Thinking in LoopBack: incrementally implement the features
 - [x] #547 Thinking in LoopBack: Custom Sequence
 - [x] #548 Thinking in LoopBack: Preparing your API for consumption  (*p2 item*)
 - [x] #549 Thinking in LoopBack: Closing thoughts
 - [ ] #550 Thinking in LoopBack: clean up "Smoke test API"  (*p2 item*)

**Comment by bajtos** [comment]
Converting this GH issue into an epic. See the updated description for a list of sub-stories.

**Comment by dhmlau** [comment]
The p1 sub-items are done. Marking this as `p2`.

**Comment by dhmlau** [comment]
Closing this epic and keeping the #550 item.
