### ISSUE TITLE
How to migrate LB3 components

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3955]
_This is a follow-up for #3718 and #3922._

Write content for `docs/site/migration/extensions.md`, explain how can users migrate their custom components to LB4.

## Acceptance criteria

- [ ] How to rewrite components from LB3 to LB4 style
- [ ] How to migrate applications using such components
- [ ] What's our advice for apps using official loopback components like `loopback-component-storage`?

**Comment by bajtos** [comment]
This will require a bit of research first, we need to build a better understanding of what can LB3 components contribute and how to map that to LB4.

You can use the following npm search to find existing LB3 mixins as examples to help us better understand different usage patterns we need to cover in our migration guide:

https://www.npmjs.com/search?q=loopback%20component
