### ISSUE TITLE
How to migrate apps using loopback-component-passport

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#3958]
_This is a follow-up for #3718 and #3922._

Write content for `docs/site/migration/auth/passport.md`, explain how to migrate LB3 applications using [loopback-component-passport](https://github.com/strongloop/loopback-component-passport) to LB4.

I think the long term goal should be to move our users to [`@loopback/authentication-passport`](https://github.com/strongloop/loopback-next/tree/master/extensions/authentication-passport).

~~For short to medium term, while they are running both LB3 and LB4 app at the same time, we can show them how to use Passport as Express middleware, see https://github.com/strongloop/loopback-next/issues/3947.~~ 
scoped to #5005

## Acceptance criteria

Migration guide describing manual steps for the following scenarios:

- [x] LB4-only, this should show how to migrate to our recommended setup. (PR : https://github.com/strongloop/loopback-next/pull/4899)
     - [x]   add support for oauth2 redirection in loopback strategy (https://github.com/strongloop/loopback-next/issues/4902)
     - [x]   create example app for login with facebook and google, similar to https://github.com/strongloop/loopback-example-passport (https://github.com/strongloop/loopback-next/issues/2624)
     - [x]  enabling client sessions in the example app to save user profiles on login and delete session on logout

- [x] ~~Both LB3 and LB4 applications running in the same process, we want to use a single passport configuration to secure both LB3 and LB4 routes.~~
scoped into a separate issue: https://github.com/strongloop/loopback-next/issues/5005

**Comment by deepakrkris** [comment]
closing this epic as the scoped out issue https://github.com/strongloop/loopback-next/issues/5005 is not closely related to the original story.
