### ISSUE TITLE
Decorators for controller methods

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#404]
Define and implement decorators allowing Controller authors to describe the endpoints, their arguments and return values in a code-first way.

```ts
class HelloController {
  constructor() {
    this.messages = new Repository('messages');
  }
  @get('/messages')
  @param.query.number('limit')
  list(limit = 10) {
    if (limit > 100) limit = 100; // your logic
    return this.messages.find({skip, limit});
  }
}
```

See [wiki](https://github.com/strongloop/loopback-next/wiki/Controllers#writing-controller-methods) for more details.

**Tasks**

 - [x] #459 - Add shortcuts for HTTP verbs: `@post`, `@put`, `@patch`, `@delete`
 - [x] #457 - First cut of param decorators - `@param(spec)` as the generic implementation, `@param.query.number(name)` as a short-cut
 - [x] #457 - Additional shortcuts for types (when `in` is not `body`): `string`, `number`, `integer`, `boolean`
 - [x] #460 - Additional shortcuts for `in` values: `@param.body`, `@param.formData`, `@param.header`, `@param.path`
- [x] #462 - Merge `@param` data with `spec` argument of `@operation`

Out of scope:
 - `file` type (not supported by our parameter parser yet)
 - `array` type shortcut - requires extra `items` spec, at this point I think it's better to use the longer `@param(spec)` format.

**Comment by superkhau** [comment]
Timebox to 5

**Comment by raymondfeng** [comment]
We can start with similar decorators as https://github.com/thiagobustamante/typescript-rest/blob/master/src/decorators.ts, which are inspired by JAX-RS.

**Comment by bajtos** [comment]
Thank you @jonathan-casarrubias for a thoughtful comment, I understand your concerns.

> if we would be able to explore the entire App, similar to what we had in LB<4 app.models where you could iterate the models and scopes, etc....

One option that's already available in loopback-next is to inspect bindings matching a key pattern. For example, `app.controller()` is binding the controller class to `controllers.${controller.name}` under the hood. Repositories (representing models) are bound similarly.

On the other hand, the routes (even Controller-based ones) are registered directly with the http router/handler, therefore they are not inspectable via IoC context. However, I think it should be reasonably easy to expose an API allowing components to access the list of all registered routes. This list represents the exact REST API as it is exposed by the application.

Having wrote that, I think there is one bigger concern that will probably require SDK generators to rethink their strategy. In LoopBack 3.x, we have a single entity mixing both Model (data persistence) and Controller (public API). When a shared Model method used a complex data type, this type was almost always the same Model. In LoopBack Next, we have decoupled Models and Controllers. A controller can define arbitrary REST API and use different data types for requests/responses, not all of these types has to map 1:1 to Models.

> I've already put an effort on https://github.com/mean-expert-official/openapi-sdk-builder so we can build an SDK from the open-api spec... But that is too limited

Vanilla open-api-spec 2.x is actually not enough to build the server either. We are adding custom extensions like `x-method-name` that allow us to map flat list of operations into a more structured Controller+method layout. 

I believe it will be possible to use a similar approach for SDK builders too, ideally leveraging the same extensions as the server is using.

> more if $ref is not yet supported.

I think we will need to add support for `$ref` soon, it's just matter of timing/prioritization. 

> 2.- Regardless the SDK, in order to rewrite FireLoop on top of LB4 by creating components https://github.com/strongloop/loopback-next/wiki/Using-Components, we need a way to explore the entire App, controllers, models, scopes and repositories from those componentes.

Makes sense. Let's discuss "inspectability" in a new issue to keep the discussion here on the topic of controller decorators. The new issue: https://github.com/strongloop/loopback-next/issues/461

> Right now I'm unaware of how you are tying the configurations after you pass those through a decorator.

Here is the code processing decorators (and other ways how to define HTTP routes) and setting up a http handler: [packages/core/src/application.ts#L102-L130](https://github.com/strongloop/loopback-next/blob/57a6e4ddd922514de332606d7d69668f2d20c875/packages/core/src/application.ts#L102-L130)

As I wrote earlier, I think it will be best to make routes inspectable, so that tools like the SDK builder can get a list of all HTTP endpoints, similarly to how LoopBack/strong-remoting 3.x allowed tools to get a list of all shared methods.
