### ISSUE TITLE
Monthly Milestone - Dec 2019 🌲⛄️🎁

### ISSUE THREAD

**Issue by agnes512** [strongloop/loopback-next#4236]
## December Milestone

- Community Support: focus on triaging and PR reviews in
  `loopback-datasource-juggler` and `loopback-connector-postgresql`

### Goals
Inclusion of related models [MVP]
  - [x] Include related models with a custom scope #3453

Authentication & Authorization

  - [x] Add user profile factory for authentication modules https://github.com/strongloop/loopback-next/issues/3846
  - [x] Contribute OpenAPI spec pieces from extensions https://github.com/strongloop/loopback-next/issues/3854

Add support for Partitioned Database
  - [x] Blog post https://github.com/strongloop/loopback-connector-cloudant/issues/231

From model definition to REST API with no custom repository/controller classes
- [x] Model API booter & builder https://github.com/strongloop/loopback-next/issues/3736

Migration guide between LB3 to LB4
  - [ ] Spike: Migration guide from LB3 - Authentication & authorization
        https://github.com/strongloop/loopback-next/issues/3719

Docs
  - [x] PR: How to scaffold, run, debug, test, and deploy a LoopBack 4 application using Appsody CLI https://github.com/strongloop/loopback-next/pull/4215

_Miscellaneous_
- [x] Reject create/update requests when data contains navigational properties https://github.com/strongloop/loopback-next/issues/3439
- [ ] :running: API Explorer ignores filter options where, fields, and order #2208
- [x] Column is always integer when running `npm run migrate`
        https://github.com/strongloop/loopback-next/issues/2398
- [x] Spike: Discover and define models at runtime https://github.com/strongloop/loopback-next/issues/2484

### Stretch Goals

Bug fixes
  - [x] Id deleted on update on MongoDB #3267
  - [x] TodoList tutorial - GET ​/todos​/{id}​/todo-list gives unexpected
        response #4147
  - [ ] lb4 repository,model,controller commands generate artifacts with 'lint'
        issues https://github.com/strongloop/loopback-next/issues/4205

~From model definition to REST API with no custom repository/controller
      classes https://github.com/strongloop/loopback-next/issues/2036~ . **Moved to be stretch goals for 2020Q1 roadmap**

  - [ ] ~Add CrudRestApiBuilder to `@loopback/rest-crud`,
        https://github.com/strongloop/loopback-next/issues/3737~
  - [ ] ~Example app showing CrudRestApiBuilder
        https://github.com/strongloop/loopback-next/issues/3738~

Migration guide between LB3 to LB4 [MVP]
  - [x] How to migrate datasources from LB3 to LB4 #3946
  - [ ] How to migrate boot scripts #3957
  - [ ] How to migrate user-defined model methods #3949

**Comment by agnes512** [comment]
:tada:
