### ISSUE TITLE
Monthly Milestone - January 2020 ❄️🎆🎉

### ISSUE THREAD

**Issue by emonddr** [strongloop/loopback-next#4376]
## Overview

- Take some time to:
  - fix bugs, improve developer experience, fix docs
  - triage open issues across all the repos, not just `loopback-next`
- Migration work continues to be one of the focus
- Focus on issues/PRs for loopback-connector-mongodb

## Goals

- Migration guide between LB3 and LB4 MVP #453

  - [x] How to migrate boot scripts #3957
  - [x] :running: Spike: Migration guide from LB3 - Authentication & authorization
#3719
  - [x] How to migrate user-defined model methods #3949
  - [x] How to migrate remoting hooks #3950

- Improve developer experience

  - [x] :running: Expose isActive() method in Transaction interface #3471
  - [x] Missing model.ts after running lb4 openapi command #4135
  - [x] Model strict: false is ignored with Postgre SQL repository #4042

- Bugs

  - [x] Docs: Improve TodoList Tutorial instructions and completed tutorial
        'lb4 example todo-list' #4161
  - [x] ~~LB3 - Relations on uuid https://github.com/strongloop/loopback/issues/4287~~

- Update dependencies

  - [x] chore: update dependency change-case to v4 #4233
  - [x] update dependency ts-morph to v6 #4274

- [x] :running: [spike] API Connect / LoopBack 4 integration #4115

- _Miscellaneous_

  - [ ] :running: API Explorer ignores filter options where, fields, and order #2208
  - [x]  lb4 repository,model,controller commands generate artifacts with 'lint'
issues #4205
  - [ ] :running: npm test hangs infinitly on windows #4425

## Stretch goals
  
- Create models & REST APIs dynamically at runtime

  - [ ] ~~Dynamic binding/rebinding of controllers after app start #433~~

- Migration guide between LB3 and LB4 MVP #453

- [ ] How to map LB3 CLI commands to LB4 CLI #3953
- [ ] How to migrate CRUD Operation Hooks #3952

- Create models & REST APIs dynamically at runtime

  - [ ] How to build models, repositories and controllers dynamically at runtime
        #4296 [needs estimate]

- Bugs

  - [ ] [community contribution?] Preserve custom type of auto-generated id
    property #3602 [needs estimate]
  - [ ] :running: Column names in lowercase using lb4 discover method -
        SQL connector #3343
  - [x] lb4 relation should discard changes when something failed #3287 

- PR reviews
  - [ ] feat(extension-logging): add integration with winston and fluentd
        logging, https://github.com/strongloop/loopback-next/pull/4117
  - [ ] [RFC] feat: add base code for the image of Appsody LoopBack stack,
        https://github.com/strongloop/loopback-next/pull/4250 [draft pr still in discussion]
