### ISSUE TITLE
Tutorial for persisting data with Repository

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#446]
# Description/Steps to reproduce
For beta release, we need a few tutorials/examples for persisting data using Repository, similar to https://github.com/strongloop/loopback-next-hello-world.  It would contain step-by-step instructions in how to build one.  

- [ ] for SQL DB with legacy juggler
- [ ] for noSQL DB with legacy juggler
- [ ] for REST / SOAP (possibly?) 

Some of the contents already exist in the wiki:
https://github.com/strongloop/loopback-next/wiki/Persisting-Data-with-Repositories

**Comment by dhmlau** [comment]
We already have tutorials for todo and soap calculator example.  Closing it as resolved.
