### ISSUE TITLE
APIConnect / LoopBack 4 integration

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-next#4516]
## Use Cases

Source Epic: https://github.ibm.com/velox/ui/issues/19306

APIC 5.0 had options to import Open API spec (v2) from an existing LoopBack 3 Application.
(https://www.ibm.com/support/knowledgecenter/en/SSFS6T/com.ibm.apic.toolkit.doc/capim_cli_product_yaml_example.html ). 
APIConnect v2018 now has limited support to import OpenAPI -v3 (https://www.ibm.com/support/knowledgecenter/en/SSMNED_2018/com.ibm.apic.toolkit.doc/rapic_oai3_support.html). 

LoopBack provides extensive support for creating OpenAPI v3 APIs.

APIC 2018 / LoopBack 4 integration is a proposed strategic solution to allow creating new LoopBack 4 APIs and importing existing LoopBack 4 APIs.

## Acceptance criteria
- [x] APIC / LoopBack check integration options and limitations https://github.com/strongloop/loopback-next/issues/4115
- [ ]  ~Toolkit commands to digest LoopBack API specifications per APIC format https://github.ibm.com/velox/platform/issues/1559~  
- [x] 🏃 APIC OpenAPI enhancer. See PR: https://github.com/strongloop/loopback-next/pull/4851
- [x]  SPIKE : End to End test Shopping example in cloud with APIConnect https://github.com/strongloop/loopback-next/issues/4498
- [x]  Update APIC knowledge center on how to import LoopBack API spec, once the above two tasks are completed

**Comment by dhmlau** [comment]
> Toolkit commands to digest LoopBack API specifications per APIC format https://github.ibm.com/velox/platform/issues/1559

@deepakrkris, could you please follow up in Feb? If that's something falls under the LB team (which is likely the case), we probably need a separate task for the implementation.

**Comment by dhmlau** [comment]
Got a confirmation from Pramodh (OM) on the import API scenario. The plan is to use the [APIC OpenAPI enhancer](https://github.com/strongloop/loopback-next/tree/master/extensions/apiconnect) to make OpenAPIv3 spec coming from LB to be able to get imported to API Connect. 

In this case, the test we're going to do in https://github.com/strongloop/loopback-next/issues/4498 and potential docs and articles will go for this route. Thanks!

**Comment by deepakrkris** [comment]
@dhmlau issue #4498 (End to End test Shopping example in cloud with APIConnect) is completed now.

**Comment by dhmlau** [comment]
Closing as done. Thanks @deepakrkris and @raymondfeng! 👏
