### ISSUE TITLE
Monthly Milestone - February 2020  💝 🔆 ☕️

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#4543]
## Overview
- continue to focus on the migration guide: general runtime and authentication+authorization

## Goals

- [ ] Migration guide between LB3 and LB4 MVP #453
  - [ ] 🏃How to migrate CRUD Operation Hooks #3952
  - [ ]  🏃How to migrate model mixins #3951
  - [x] Spike: how to import LB3 models extending a custom base model #3813
  - [ ] 🏃 [migration/auth] Migrate
        https://github.com/strongloop/loopback-example-access-control to LB4
        #4520

- [x] Tooling around migration
  - [x] 🏃LB3 model import: preserve connector-specific metadata in property
        definitions #3810

- [x] Create models & REST APIs dynamically at runtime
  - [x] 🏃Dynamic binding/rebinding of controllers after app start #433

- [x] Shopping app web site
  - [x]  Shopping App Website: Installation/setup documentation
        https://github.com/strongloop/loopback4-example-shopping/issues/477

- [x] Miscellaneous
  - [x] API Explorer ignores filter options where, fields, and order #2208
  - [x] npm test hangs infinitly on windows #4425
  - [x] Run shared tests from both v3 and v4 of juggler
        https://github.com/strongloop/loopback-connector-db2/issues/133
  - [x] Add CrudRestApiBuilder to `@loopback/rest-crud` #3737
  - [x] Column names in lowercase using lb4 discover method - SQL
        connector #3343

- PR reviews:
  - [x] feat: adds @deprecated convenience decorator #4415
  - [ ] feat: adds utility launch for debugging a single test file #4432
  - [x] Preserve custom type of auto-generated id property #4270
  - [x] feat(extension-logging): add integration with winston and fluentd
        logging #4117

## Stretch Goals
- CI

  - [x] :running: [CI] Postgresql downstream tests failed
        https://github.com/strongloop/loopback-datasource-juggler/issues/1816
  - [x] [DashDB] Run shared tests from both v3 and v4 of juggler
        https://github.com/strongloop/loopback-connector-dashdb/issues/79

- Bug fixes
  - [ ] :running:  Belongs-To relation tries to resolve for foreign key NULL #4372
  - [ ] ~Log extension is not printing any logs #2173~ Out of scope for Q1

- Migration guide between LB3 and LB4 MVP #453
  - [ ] Migration Guide: Discuss life cycle differences between LB3 and LB4
        #3935
  - [ ] Which official LB3 components are not planned in LB4 #3956

- [ ] ~APIC Integration #4516~
  - [ ] ~[Spike] End to End test Shopping example in cloud with APIConnect
        #4498~ Out of scope for Feb. After discussion with team and APIC team, we may not need this.

## Looking for community contributions
_Community contributors: Want to contribute but don't know where to start? Here is our wish list for this month:_

- [ ] Add bearer auth scheme as the default security scheme #4386
- [ ] :running: Add OpenAPI enhancer service in @loopback/rest #4380 
- [ ] Sugar decorators for Filter and Where parameters #1749
- [ ] Model.toObject() should preserve prototypes (e.g. Date and ObjectID values) #3607

**Comment by dhmlau** [comment]
Moved the slipped tasks to March. Closing Feb milestone. Thanks.
