### ISSUE TITLE
LoopBack-next getting started tutorial

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#463]
_From @bajtos on July 18, 2017 17:24_

_From @superkhau on March 20, 2017 22:37_

Deadline: ???

As a LoopBack user
I want to try out a tutorial
So that I can learn the basics of LoopBack-next

# Story map
&nbsp;|&nbsp;|&nbsp;
---|---|---
Go to [loopback.io/getting-started](http://loopback.io/getting-started) | Follow page-by-page tutorial on loopback.io | End the tutorial with next steps
Go to [loopback-next/wiki](http://github.com/strongloop/loopback-next/wiki/getting-started)

_Copied from original issue: strongloop-internal/scrum-asteroid#27_

_Copied from original issue: strongloop-internal/scrum-apex#281_

_From @bajtos on July 26, 2017 12:15_

## Acceptance Criteria

1. Setup an empty LoopBack.next project (downloading an empty "sandbox" repo from GitHub is an acceptable solution to me)
2. Define my first REST API endpoint (via a Controller)
3. Define a Model
4. Persist my new Model in a database (via a Repository and a connector?)
5. Implement my controller method from step 2 by calling a model/repository methods.
6. Start the app, open SwaggerUI to visualize my new API and make few test requests to play with it.

**Comment by b-admike** [comment]
- Use tags or branches to show each step of the tutorial
    - Reference: https://github.com/angular/angular-phonecat

**Comment by Setogit** [comment]
The LoopBack Next wiki is the entry point to LB Next documentation: https://github.com/strongloop/loopback-next/wiki/

There is a section called `Take the tutorial` : https://github.com/strongloop/loopback-next/wiki/Take-the-tutorial

As you see there, `the tutorial` *is` the hello-world: https://github.com/strongloop/loopback-next-hello-world

There are two parts in hello-world: coding and documentation.

This task is the coding part of the tutorial.  The documentation part is https://github.com/strongloop/loopback-next/issues/499

__________
As of Aug. 10, 2017,  significant portion of the hello-world coding is done as the following branch: https://github.com/strongloop/loopback-next-hello-world/tree/add-authentication-component
In the branch: these three items are`done` except for an issue in the interaction with Authentication component.
- [x] controllers:  OpenAPI v2 compatible spec, spec validation test
- [ ] component : use Authentication component
- [x] sequence : custom sequence with the Authentication component

The remaining items are:
- [ ] Repository/Model : integrate the example implementation from loopback-next/packages/repository/examples: https://github.com/strongloop/loopback-next/tree/master/packages/repository/examples
- [ ] the swagger UI item in the acceptance criteria: Start the app, open SwaggerUI to visualize my new API and make few test requests to play with it.

**Comment by dhmlau** [comment]
@b-admike , what's left to be done here? 
Would it affect the write-up of https://github.com/strongloop/loopback-next/issues/499?

**Comment by b-admike** [comment]
At the moment, I have all the pieces needed for this story, but I'd have to refactor `hello-world` app to use our new rest package.
