### ISSUE TITLE
Monthly Milestone - March 2020 👾⏳🐨

### ISSUE THREAD

**Issue by agnes512** [strongloop/loopback-next#4767]
## Overview

- Migration guide: Stop starting, start finishing!

## Goals

- [ ] Migration guide https://github.com/strongloop/loopback-next/issues/3935

  _General runtime_

  - [x] Which official LB3 components are not planned in LB4 #3956 (from Feb
        milestone)
  - [ ] 🚶Migration Guide: Discuss life cycle differences between LB3 and LB4
        #3935 (from Feb milestone)

  _Authentication & Authorization_

  - [x] [migration/auth] Create a guide to describe how to migrate LB3 User
        based authentication to LB4 #4521
  - [ ] 🏃 How to migrate apps using loopback-component-passport #3958
  - [x] ~[migration/auth] Describe how to simulate ACLs with LB4 authorization
        #4522 .~  [Only shopping app related changes left. Moved to Q2]

- [x] Miscellaneous
  - [x] Belongs-To relation tries to resolve for foreign key NULL #4372
  - [x] How to build models, repositories and controllers dynamically at runtime
        #4296
  - [x] LB3 is in Maintenance LTS now! strongloop/loopback#4306
  - [x] Extract the jwt authentication to a local component for the auth migration example app #4753

## Stretch Goals

- [ ] Internal Tooling

  - [ ] Switch contribution method from CLA to DCO #2292

- Spikes

  - [ ] Spike: robust handling of ObjectID type for MongoDB #3456

- [x] Bugs
  - [x] Broken anchor link https://github.com/strongloop/loopback.io/issues/907
  - [x] How to define a model @property that allows any scalar value? #4255
  - [x] ID automatically generated by PostgreSQL becomes undefined #4751
  - [x] Identifier gets discarded after running migration #4744

## Looking for community contributions

_Community contributors: Want to contribute but don't know where to start? Here
is our wish list for this month:_

- [ ] :running: [Spike] How to migrate Angular 1.x and 2+ LB3 client #4610
- [ ] Model.toObject() should preserve prototypes (e.g. Date and ObjectID
      values) #3607
- [ ] Complex OpenAPI Validations with @property #1624
- [ ] default values added for new required columns when running `autoupdate()` https://github.com/strongloop/loopback-connector-postgresql/pull/418

**Comment by agnes512** [comment]
Closing as done
