### ISSUE TITLE
Monthly Milestone - April 2020 💪😷🐣

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#5010]
## Overview
With COVID-19 impacting the maintainers at different levels, we will be committing less story points to give us more flexibility.

The goals for this month would be to:
- Aim at finish the [Migration guide epic](https://github.com/strongloop/loopback-next/issues/3935) except for the [migrate LB3 components related tasks](https://github.com/strongloop/loopback-next/issues/3955).

## Goals

- [ ] Migration guide #3935

  - [x] Migration Guide: Request-response cycle #4836
  - [x] docs: migrate loopback-example-passport repo as lb4 example #4899
  - [x] Migration Guide: Boot up #4838
  - [x] Migration Guide: Custom validation #4837
  - [ ] :running: Spike: How to migrate LB3 components #4099
  - [x] How to map LB3 CLI commands to LB4 CLI #3953
  - [x] 🏃~Spike: How to migrate apps using loopback-component-oauth2 #3959~ issue no longer applicable

- [x] APIC/LB integration
  - [x] [Spike] End to End test Shopping example in cloud with APIConnect #4498

- [x] Documentation
  - [x] Docs: Add "Working with Data" section #2527 

- [x] Miscellaneous
  - [x] Extract the jwt authentication to an extension module #4903

- [ ] PR reviews
  - [ ] feat(repository): hasManyThrough #4438
  - [x] Add tsdoc package documentation #4711
  - [x] feat(rest): add openapi schema consolidation #4365

## Stretch goals
- [x] Migration guide
  - [x]  Spike: how to run LB3 tests from LB4 when LB3 is mounted on the LB4 app #5004

- [x] Docs
  - [x] Docs: how to use OpenAPI connector #4488

- [ ] LB4 adoption
  - [ ] 🏃Blog on what LB can offer on top of Express #4852

- [ ] APIC/LB integration
  - [ ] [Blog] Managing your APIs: From LoopBack to IBM API Connect #4901

- [ ] Miscellaneous

  - [x] Custom visual style of REST API Explorer #2023
  - [ ] Spike: robust handling of ObjectID type for MongoDB #3456
  - [ ] 🏃Enable TypeScript Project References #2609

## Looking for community contributions
- OpenAPI related
  - [x] Complex OpenAPI Validations with @property #1624
  - [ ] :running: Add bearer auth scheme as the default security scheme #4386
  - [ ] OpenAPI schema generation and model inheritance #3293

- Miscellaneous
  - [ ] default values added for new required columns when running
        `autoupdate()`
        https://github.com/strongloop/loopback-connector-postgresql/pull/418
  - [ ] Model.toObject() should preserve prototypes (e.g. Date and ObjectID
        values) #3607
  - [ ] :running: [Spike] How to migrate Angular 1.x and 2+ LB3 client #4610
  - [ ] :running: Document how to send emails in LB4 #1979

**Comment by agnes512** [comment]
Closing as done
