### ISSUE TITLE
Monthly Milestone - May 2020 ☀️ 🌎 🍀

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#5301]
### Overview

The goals for this month would be to:

- Finish migration guide - depending on the tasks created from the spikes
- Work on outstanding docs and bug fixes

### Goals

- [x] Migration Guide

  - [x] Spike: How to migrate LB3 components #4099
  - [x] Spike: How to run LB3 app tests when the app is mounted in a LB4 project
        #5004
    - [x] Documentation for Migrating LB3 Tests Mounted on an LB4 App #5298 
    - [x] Bind Mounted LB3 Models to LB4 Context #5299
    - [x] Add Example LB3 Tests to lb3-application  #5300 

- [x] Feature Parity

  - [x] Model.toObject() should preserve prototypes (e.g. Date and ObjectID
        values) #3607

- [x] Bugs

  - [x] defining a nested array model property using @property.array decorator
        crashes the app #4754

- [x] Docs / Blogs

  - [x] Blog on what LB can offer on top of Express #4852
  - [x] [Docs] Add debug string information #4845
  - [x] [Docs] Add "error handling" page #4846
  - [x] 🏃 [Blog] Managing your APIs: From LoopBack to IBM API Connect #4901

- [ ] Miscellaneous

  - [ ] 🏃 How to build models, repositories and controllers dynamically at runtime
        #4296

- [ ] PRs to review
  - [ ] feat(repository): hasManyThrough #4438
  - [ ] [RFC] Enable parallel mocha testing #5011
  -  ~feat(http-server): adds http/2 support #4989~ blocked, waiting for Express's support.

### Stretch Goals

Moved these 2 stories to stretch goals after adding the follow-up stories for #5004 as committed.

- [ ] Spike: robust handling of ObjectID type for MongoDB #3456
- [ ] Integration with TypeORM #4853

- [ ] Docs / Blogs

  - [ ] [Docs] Clean up extension template and docs #5336 
  - [ ] [Docs] Add "project layout reference" page #4847
  - [x] [Docs] :running: Postgresql connector docs should cover LB4 content #4877
  - [ ] [Docs] MongoDB connector docs should cover LB4 content #4879 

- [ ] Bugs

  - [ ] Failed to exclude properties by setting false in `fields` filter via url
        #4992

- [ ] From relation definition to REST API #2483

  - [ ] [SPIKE] HasMany relation definition to REST API with auto-generated
        repository/controller classes #3896

- [x] 🏃Enable TypeScript Project References #2609

### Community Contribution

- [ ] :running: [Spike] How to migrate Angular 1.x and 2+ LB3 client #4610
- [ ] :running: Document how to send emails in LB4 #1979
- [ ] :running: Polymorphic relation type #2487
- [x] Model.toObject() should preserve prototypes (e.g. Date and ObjectID
      values) #3607
- [x] 🏃 Add bearer auth scheme as the default security scheme #4386
- [ ] OpenAPI schema generation and model inheritance #3293
- [ ] default values added for new required columns when running autoupdate()
      strongloop/loopback-connector-postgresql#418

**Comment by dhmlau** [comment]
Closing as May is done.
