### ISSUE TITLE
Monthly Milestone - June 2020 💪🏻 🌏 🌳

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-next#5607]
## Overview

Finish Q2 release.

Removed "Spike: robust handling of ObjectID type for MongoDB" per @bajtos' comment on Slack.

## Goals

- [ ] Clean up extension template and docs #5336
- [x] Failed to exclude properties by setting false in `fields` filter via url
      #4992
~~- [ ] Spike: robust handling of ObjectID type for MongoDB #3456~~
- [ ] 🏃 Integration with TypeORM #4853
- [x] Continue with feat(repository): hasManyThrough #4438
- [ ] PRs to review
  - [ ]  🏃 feat(graphql): add an extension for type-graphql integration #5545
  - [ ] community PRs
        https://github.com/strongloop/loopback-next/pulls?q=is%3Apr+is%3Aopen+label%3Acommunity-contribution

## Stretch Goals

- [ ] Documentation improvement

  - [x] [Docs] MongoDB connector docs should cover LB4 content #4879
  - [x] [Docs] MySQL connector docs should cover LB4 content #4878
  - [x] [Docs] Oracle connector docs should cover LB4 content #4880
  - [ ] [Docs] Add "project layout reference" page #4847

## Contributions from Community

- [ ] [Workshop] From API to UI: LoopBack with Angular with client generator
      #4849
