### ISSUE TITLE
Internal tooling improvements 2020Q3

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#5669]
Improve the internal tooling we use to develop LoopBack 4 (2020Q3 edition).

- [x] Enable parallel mocha testing #5011
- [ ] Move slow tests from `npm test` to a different test task #5670
- [ ] Spike: Switch from lerna to pnpm workspaces #5671

**Comment by marioestradarosa** [comment]
@bajtos  Does mocha has now support for parallel testings ?

**Comment by raymondfeng** [comment]
@marioestradarosa We have https://github.com/strongloop/loopback-next/pull/5011. It will be retested and landed once a new release of Mocha is published.

**Comment by dhmlau** [comment]
Closing for Q3 scope.
