### ISSUE TITLE
Monthly Milestone - July 2020 ☀️🍉🍺

### ISSUE THREAD

**Issue by agnes512** [strongloop/loopback-next#5837]
# Monthly Milestone - July 2020

## Overview

Focus on:

- documentation improvements
- reduce backlog of PRs waiting to be reviewed

## Goals

- [x] Docs improvements #5113

  - [x]  Hide @loopback/openapi-v3 from docs, examples and CLI templates #5692
  - [x] Improve and refactor the authentication documentations #5294
  - [x] Add "How the documentation is organized" section #5752

- [x] Feature parity

  - [x] Continue with feat(repository): hasManyThrough #4438

- [x] Integration with TypeORM #4853 

- [x] Fix GVT issues

  - [x] [GSSC-GVT]English String when input command apic lb4 app -h #5654
  - [x] [GSSC-GVT]English String when input command apic lb4 repository #5656
  - [x] [GSSC-GVT]English String when input command apic lb4 model #5657
  - [x] [GSSC-GVT]English String when input command APIC apic lb4 interceptor
        #5658

- [x] Bugs

  - [x] Regression: MongoError: unknown operator: \$\$eq
        strongloop/loopback-connector-mongodb#532

- [ ] PRs to review
  - [x] Add "signup" / create user in authentication-jwt module #5763 
  - [ ] 5187 jwt refresh token Feature #5589
  - [x] feat(pooling): add an extension to provide pooling service #5681
  - [ ] [RFC] Define sequence actions as middleware #5366
  - [x] [RFC WIP] feat(typegoose): add a component for typegoose/mongoose
        integration #5152

## Stretch Goals

- [ ] Docs Improvement
  - [x] :running: How to configure a custom table/collection name different from model class name #2197
  - [x] :running: couchDB connector docs #5267
  - [ ] Add "project layout reference" page #4847
  - [ ] Add missing LoopBack 4 Types docs #5063

- [ ] Feature parity

  - [ ] Execute raw NoSQL queries (e.g. MongoDB) #3342

- [x] Chores/Tooling improvements

  - [x] update dependency mem-fs-editor to v7 #5624
