### ISSUE TITLE
[EPIC] Test/Enable Node.js 14 support for connectors 

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#6019]
Similar to https://github.com/strongloop/loopback-next/issues/3072

After https://github.com/strongloop/loopback-datasource-juggler/issues/1841 has landed to enable Node.js 14 support, the next step is to test and add support for Node.js 14.x for the connectors. 

### Acceptance Criteria
For the following connectors, test locally on Node.js 14 and see if all tests passed.  
- If yes, add Node.js 14 to CI 
- If not, try to fix it for simple fixes.  If you don't think you can fix it in a day, open a new issue to keep track of it.

Here is the list of connectors:

_SQL connectors:_ 
- [ ] loopback-connector
- [ ] loopback-connector-mysql
- [ ] loopback-connector-postgresql
- [ ] loopback-connector-mssql
- [ ] loopback-connector-oracle
- [ ] loopback-connector-db2 (need to find out if ibm_db supports Node.js 14)

_noSQL connectors:_ 
- [ ] loopback-connector-mongodb
- [ ] loopback-connector-couchdb2
- [ ] loopback-connector-cloudant
- [ ] loopback-connector-cassandra

_service connectors:_ 
- [ ] loopback-connector-remote
- [ ] loopback-connector-rest
- [ ] loopback-connector-soap
- [ ] loopback-connector-jsonrpc
- [ ] loopback-connector-openapi
