### ISSUE TITLE
Monthly Milestone - August 2020 ☀️🌵🌻🌴

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-next#6028]
### Overview

- In August, loopback team's focus will be the documentation improvements.

### Goals

- [x] Documentation improvement

  - [x] 🏃‍♂️ docs: improve the structure of "Behind the scenes" sidebar + find a
        better name #5776
  - [x]  docs: improve the structure of "Usage scenarios" (how-to guides) sidebar
        #5777
  - [x]  [Spike] docs: untangle connector reference into reference, how-to guides
        and tutorials #5961
  - [x] Rename "legacy juggler bridge" mentioned in docs #5558
  - ~[x] Add Couchdb connector docs #5267~ DONE in July
  - [x] [APIDocs] Table not showing properly when it includes code snippet #5756
  - [x] 🏃‍♂️ Clean up extension template and docs #5336

- [x] Bugs

  - [x] includeRelations bug #4547

- [x] Miscellaneous

  - [x] 🏃‍♂️CLA/DCO switch strongloop-internal/scrum-apex#436
  - [x]  Spike: robust handling of ObjectID type for MongoDB #3456

- [ ] PRs to review:
  - [x] feat: introduce middleware based sequence for REST #5366
  - [ ] feat(graphql): add an extension for type-graphql integration #5545
  - [x] feat(authentication): add support for multiple strategies on same method
        #5735
  - [x] 5187 jwt refresh token Feature #5589
  - [ ] [RFC WIP] feat(typegoose): add a component for typegoose/mongoose
        integration #5152

### Stretch Goals (Community contribution is welcome!)

- [ ] Documentation improvement

  - [x]  🏃‍♂️Improve loopback4 authorization docs of using the component #5441
  - [ ] Blogpost: what are our current plans for juggler modernization #5956
  - [x] 🏃‍♂️ Add "project layout reference" page #4847
  - [x]  Add missing LoopBack 4 Types docs #5063

- [ ] Feature parity
  - [ ] 🏃‍♂️Execute raw NoSQL queries (e.g. MongoDB) #3342

- [ ] Dependency upgrade
  - [ ] Update to yeoman 3.x https://github.com/strongloop/loopback-next/pull/6049

**Comment by hacksparrow** [comment]
What's left to review in https://github.com/strongloop/loopback-next/pull/5152? I think, we have provided enough feedback to consider it as reviewed. @dhmlau @jannyHou
