### ISSUE TITLE
Drop support for Node.js 6.x

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#611]
Considering that Node.js 6.x will enter maintenance mode long time before our expected GA release, we think it makes sense to require LoopBack Next users to run on Node.js 8.x or newer.

**Tasks**

 - [x] Drop Node.js 6.x from Travis-CI and AppVeyor configs
 - [x] Change "engines" field in `package.json` to `"node": ">=8"` 
 - [x] Simplify build-related tasks in both top-level and package-level `package.json` files - drop `dist6` - related targets.
 - [x] Replace all `promisify` helpers with `util.promisify` from Node.js core
 - [x] Simplify `@loopback/build`, remove scripts dealing with multiple `dist` folders and multiple `tsc` targets (es2015, es2017).
 - [x] Consider removing top-level `index*` files in each package, set `"main": "dist/index.js"`  in `package.json` instead. (This may not work.)
 - [x] Update the project template used by CLI when scaffolding new projects
 - [x] Apply the same changes to all other related repositories + review READMEs and remove mentions of Node.js 6.x:

   - [x] https://github.com/strongloop/loopback-next-hello-world
   - [x] https://github.com/strongloop/loopback4-extension-starter
   - [x] https://github.com/strongloop/loopback4-example-microservices
   - [x] https://github.com/strongloop/loopback4-example-getting-started
   - [x] https://github.com/strongloop/loopback4-extension-grpc
   - [x] https://github.com/strongloop/loopback4-extension-typeorm
   - [x] https://github.com/strongloop/loopback4-extension-mqtt
   - [x] https://github.com/strongloop/loopback4-extension-graphql
   - [x] https://github.com/strongloop/loopback4-example-log-extension
   - [x] https://github.com/strongloop/loopback4-example-rpc-server
   - [x] https://github.com/strongloop/loopback4-example-hello-world

 - [x] Review documentation on loopback.io and update all places referring to Node.js 6.x
  
 - [x] Write a blog post

**Comment by richardpringle** [comment]
Node.js 8.x is supposed to enter LTS at the end of this month. With the amount of ECMAScript changes that version 8 supports, I don't think it would make sense to release a new product with legacy support.

I would be surprised if anyone is using LoopBack 4.x with any legacy modules that require Node.js 6...

But then again... what do I know? 😉

**Comment by bajtos** [comment]
> I would be surprised if anyone is using LoopBack 4.x with any legacy modules that require Node.js 6

This is not really about using modules written in Node.js 6.x style, those should be still usable in Node.js 8.x

It's about developers that don't have a full control of their production environment - e.g. they have an operations team managing their Node.js production environment, the company may have a policy that all apps should be running on the same Node.js major version, and it may take them a non-trivial amount of effort of time to upgrade the production machines (and all deployed apps) to run on Node.js 8.x.

**Comment by proreact-mj** [comment]
We are already running LB2 on Node 8, so I'm fine with it :)

Do we know of any usual suspects (modules often used in LB apps) that still lack Node 8 support and is not expected to do so at LB4 GA?

**Comment by proreact-mj** [comment]
> It's about developers that don't have a full control of their production environment - e.g. they have an operations team managing their Node.js production environment

This is become less and less an issue with the popularity of containerization and serverless hosting options. If an operations team can provide support for the latest LTS version of Node.js, then they don't deserve the latest framework evolution 😈 IMHO

**Comment by richardpringle** [comment]
@bajtos, I know that there are some modules out there that won't even work with npm 5 on node 6. I'm guessing most (if not all) of the modules in question have native components.

As for those who do not have control over their production environments... hopefully they speak up on this thread!

**Comment by mpicard** [comment]
Or use it as leverage to get there environments upgraded 😈🙌🏻

**Comment by virkt25** [comment]
Node 8 just went LTS and Node 6 will be entering Maintenance in April 2018. I think it's better to just support Node 8 and higher.

**Comment by dhmlau** [comment]
As discussed, pulling this task into `Planning` per @bajtos  request.  This has been affecting our current development, and it's better to handle this earlier than later.

**Comment by bajtos** [comment]
> https://github.com/strongloop-archive/loopback4-extension-typeorm

I wanted to write that we don't have to change this example because it's deprecated, but then I looked at its `package.json` and found that it already supports only Node.js 8+:

https://github.com/strongloop-archive/loopback4-extension-typeorm/blob/ce1414c97670b0bd6f0648a55778a9aaa5ecc222/package.json#L9-L11

I'll mark this task as done.
