### ISSUE TITLE
Consistent file naming style

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#612]
In a slack-chat vote, we agreed to follow [Angular's file naming convention](https://angular.io/guide/styleguide#separate-file-names-with-dots-and-dashes) in our project:

```
src/decorators/authenticate.decorator.ts
```

Now we need to clean up the code in loopback-next, loopback-next-hello-world, loopback-next-extension-starter (and possibly other repositories) to follow this new style.

**Tasks**

 - [x] Document the file naming style in our docs - either here on wiki, or preferably somewhere inside http://loopback.io/doc/en/contrib/code-contrib.html
 - [x] Decide on what convention to use for test file names - see the discussion [here](https://github.com/strongloop/loopback-next-extension-starter/pull/6#discussion_r142387171) and [here](https://github.com/strongloop/loopback-next-extension-starter/pull/6#discussion_r142387402). Capture the convention in the docs.
 - [x] Update templates used by CLI to scaffold new projects, controllers, etc.
 - [x] Update loopback-next files to follow this convention
 - Update other projects to follow this convention
   - [x]  https://github.com/strongloop/loopback-next/tree/master/packages/example-hello-world
   - [ ]   ~https://github.com/strongloop/loopback4-extension-starter~ (deprecated)
   - [ ]   https://github.com/strongloop/loopback4-example-microservices
   - [x]   https://github.com/strongloop/loopback-next/tree/master/packages/example-getting-started
   - [x]   https://github.com/strongloop/loopback4-extension-grpc
   - [ ]   ~https://github.com/strongloop/loopback4-extension-typeorm~ (deprecated)
   - [x]   https://github.com/strongloop/loopback4-extension-mqtt
   - [x]   https://github.com/strongloop/loopback4-extension-graphql
      - [x] rename `graphql-component.ts` to `graphql.component.ts` 
   - [x]   https://github.com/strongloop/loopback-next/tree/master/packages/example-log-extension
   - [x]   https://github.com/strongloop/loopback-next/tree/master/packages/example-rpc-server
  
**Out of scope**

 - Automatic linter enforcing our file naming convention #833

**Comment by dhmlau** [comment]
UPDATES (03/12):
Update the original description with updated links as we've moved the repos around.

**Comment by dhmlau** [comment]
> Document the file naming style in our docs - either here on wiki, or preferably somewhere inside http://loopback.io/doc/en/contrib/code-contrib.html

I'm thinking the naming convention also applicable to users who are just creating LB4 app, not only contributing code.  I wonder if it's a better place to put in the official documentation.  Somewhere under "Best Practices" might be good, but don't know if it fits given what we have in this section.
http://loopback.io/doc/en/lb4/Best-practices-with-Loopback-4.html

**Comment by shimks** [comment]
+1 for your proposal
i'm assuming we're advocating users name their test files as such for their artifacts?: `user.controller.integration.ts`

**Comment by shimks** [comment]
Updating convention on `loopback4-example-microservices`

**Comment by shimks** [comment]
Closing since it's done
