### ISSUE TITLE
Monthly Milestone - Jan 2018

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#797]
Our focus for the upcoming 2 sprints (4 weeks) is to finish CLI tooling and implement conventional bootstrapper (`@loopback/boot`), to bring us closer to our MVP target (see https://github.com/strongloop/loopback-next/issues/696).

Legend of annotations:

Mark|Description
--|--
🏃 | work in progress
✋ | blocked task

# The plan

**Finish things in progress**

 - [ ] ✋ Switch to OpenAPI v3 for spec and routing -  https://github.com/strongloop/loopback-next/issues/753
    - track progress in comment https://github.com/strongloop/loopback-next/issues/753#issuecomment-352305467
 - [x] 🏃 TypeScript to JSON Schema - https://github.com/strongloop/loopback-next/issues/786

**CLI tooling**

  - [x] Generate Controller with CRUD methods - https://github.com/strongloop/loopback-next/issues/727

**`@loopback/boot`**

 - [ ] 🏃 Automatic configuration of controllers in Application - https://github.com/strongloop/loopback-next/issues/780
 - [ ] Automatic configuration of repositories in Application - https://github.com/strongloop/loopback-next/issues/781

**Bug fixes & community support**

 - [ ] 🏃 Circular dependencies in bindings https://github.com/strongloop/loopback-next/issues/535 - _blog post in the work_
 - 🏃 Review incoming pull requests, support extension authors, etc.

**Misc**

 - [x] Do we want a new Juggler? https://github.com/strongloop/loopback-next/issues/537

**💪💪 Stretch goals 💪💪**

 - [ ] 🏃 Add static file serving capabilities to RestServer https://github.com/strongloop/loopback-next/issues/691
 - [ ] 🏃 ~Context State and Hookless hooking https://github.com/strongloop/loopback-next/issues/139~ Not part of MVP
 - [ ] 🏃 Bring examples back into the monorepo https://github.com/strongloop/loopback-next/issues/836

It's hard to predict how much we can deliver this months because the Holiday Season (most of our team members are taking several days off), therefore this list may be less than is our actual capacity. If we happen to finish the tasks above early, then we will pick more work from our [MVP list](https://github.com/strongloop/loopback-next/issues/696).

**UPDATE (01/09)**: With the holiday seasons, most of the team was off for different extended period of time which affects the team's velocity.  As a result, we're moving the December 2017 milestone to be the Jan 2018 milestone.

**Comment by nathanfletcher** [comment]
Dope, can't wait 🙂

**Comment by dhmlau** [comment]
Closing it as Jan has passed.  
Feb milestone can be found: https://github.com/strongloop/loopback-next/issues/927
