### ISSUE TITLE
[EPIC] New web site design on LB4

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#817]
## Requirements 
Based on today's discussion with LB team,
- no change in LB3 site
- separate sites for LB3 and LB4
- use new logo and color palette coming from the voting results (https://strongloop.com/strongblog/new-loopBack-logo/)

## Acceptance Criteria
- [x] Make a new repository (v4.loopback.io) which will contain a GitHub Pages-based Jekyll site
- [ ] Create new site with the following layout:
  - [x] Home - Landing Page (/)
  - [x] Getting Started (/getting-started) - Getting started for application development (http://loopback.io/doc/en/lb4/Getting-started.html)
  - [x] Tutorial (/tutorial) - End to end tutorial for application and extension developers
  - [x] Resources (/resources) - Link to LB4 Resources / Assets
  - [ ] Contribute (/contribute) - How to contribute to LB4
  - [ ] Docs (/docs) - Documentation
- [x] Determine what domain/path the new site will live on (v4.loopback.io, loopback.io/v4, loopback.io/lb4) by team vote
- [x] Launch the page on GitHub Pages with the selected domain

## Tools
- Twitter Bootstrap v4 for the CSS/layout

**Comment by dhmlau** [comment]
Seems like we've estimated already.  Putting to backlog.

**Comment by dhmlau** [comment]
@virkt25 , i believe we've discussed the url naming proposal earlier (one of v4.loopback.io, loopback.io/v4, loopback.io/lb4).. could you please capture the decision here? thanks.

**Comment by virkt25** [comment]
The new site will be developed in a new repository `v4.loopback.io` and will have a new domain (v4.loopback.io) ... (this prevents disruptions / breakage for existing site) and once we are done development of the site (and the framework is closer to GA) this new repository will be migrated to `loopback.io` and replace the current site. 

The URL scheme for `docs` doesn't change -- follows the same format as today's site.

**Comment by dhmlau** [comment]
Removing the estimated point because this ticket turned into an epic.

**Comment by dhmlau** [comment]
Closing it as all the tasks associated with this epic are done.
