### ISSUE TITLE
Monthly Milestone - March 2018

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#937]
## Goals

- CLI Epic 
   - ~Copyright Headers in the scaffolded files: https://github.com/strongloop/loopback-next/issues/944~

- Docs epic
   - [x] Review docs: https://github.com/strongloop/loopback-next/issues/988
   - [x] Polish docs for bottom-up approach: #735 
   - [x] Spike: Move documentation to monorepo: https://github.com/strongloop/loopback-next/issues/843
   - [x] [Docs] Garden path tutorial (bottom-up approach) #729 
   - [x] ~Move contribution doc from wiki to repo #574~
   - [x] ~Docs: add a note about top-down approach not being ready yet #796~ 
 
- [x] OpenAPI 
   - [x] Switch to OpenAPI v3 for spec and routing [SLIPPED](https://www.youtube.com/watch?v=SrDSqODtEFM) - #753

- SPIKE:
   - [x] Using TypeDoc: #989 (rfeng: I think strong-docs has fixed the issue)
   - [ ] 🏃  Juggler relation spike #995 

## Stretch Goals
- [x] Rework markdown documentation scripts #1019
- [x] LB3 logo is used when creating LB4 app #972 
- [x] Bring questions back to GitHub, use GG only for announcements #47 
- [x] App template generates MIT License file without prompt #1079 

Legend of annotations:

Mark|Description
--|--
🏃 | work in progress
✋ | blocked task

**Comment by kjdelisle** [comment]
I don't expect that all of the existing Docs work in our backlog could be completed by March, as much as I wish it were so. Once we flesh out this list a bit more, we'll have a better sense of how much of that epic can be committed to in March.

**Comment by virkt25** [comment]
I'd like to propose the following for March https://github.com/strongloop/loopback-next/issues/817

**Comment by dhmlau** [comment]
@virkt25 , as much as I like to have a new site for LB4, I think we should focus on the MVP items first, at least for this milestone.

**Comment by virkt25** [comment]
#944 has been completed as part of February Milestone stretch goal.

**Comment by dhmlau** [comment]
@virkt25 , could you please update the Feb milestone to include that?  so that we know what was actually done in this month.  thanks!

**Comment by virkt25** [comment]
I added it as a stretch goal already.

**Comment by shimks** [comment]
#1079 has been done as a part of stretch goal for this milestone

**Comment by virkt25** [comment]
Closing this as March is done.
