### ISSUE TITLE
Review existing documentation

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-next#988]
## Goal
The goal is to make sure our existing documentation is accurate.  Documentation includes loopback.io and READMEs.

## Tasks
- review all of the existing documentation for LoopBack 4
- identify problems with the documentation
  - what is out of date?
  - typos
  - grammar mistakes
  - examples that do not compile
  - unclear/confusing examples

## Rules
- If you're working on this issue, assign yourself to it (**don't remove others!**)
- To grab a section:
  - Edit this issue and put your tag next to it
  - Do not claim more than one section at a time
- If the issues you find are trivial to fix, make a PR to fix it (just get it done!)
- If anything requires discussion (not trivial), then make a new issue for it and discuss it there
- Once you've gone over the whole section, mark it complete and grab a new one

## Documentation includes:
- [x] Official documentation 
  - [x] Installation (@dhmlau)
  - [x] Getting started 
      - once this PR https://github.com/strongloop/loopback.io/pull/601/files land, can revisit this page.
  - [x] Key concepts (@shimks)
    - [x] Application (@virkt25)
    - [x] Server (@dhmlau)
    - [x] Context (@shimks)
    - [x] Dependency Injection (@bajtos)
    - [x] Controllers (@shimks)
    - [x] Routes (@shimks)
    - [x] Sequence (@shimks)
    - [x] Model (@dhmlau)
    - [x] Repositories (@shimks)
    - [x] Decorators (@shimks)
  - [x] Using Components (@virkt25)
  - [x] Calling other APIs (@virkt25)
  - [x] Testing your application (@shimks)
  - [x] For current LoopBack users (@shimks)
  - [x] Command-line interface (@dhmlau)
  - [x] Best practices with LoopBack 4 (@shimks)
  - [x] Extending LoopBack 4 (@virkt25)
      - [x] Creating Components
      - [x] Creating Decorators
      - [x] Testing your extension
  - [x] Crafting LoopBack 4 (@dhmlau)
  - [x] Language-related concepts (we're thinking to remove this??) (@shimks)
  - [x] FAQ (@dhmlau)
  - [x] Reference (@dhmlau)
  - [x] Booting an Application (@dhmlau)
- [x] READMEs  
  - [x] authentication (@shimks)
  - [x] build (@dhmlau) 
  - [x] cli (@dhmlau)
  - [x] context (@virkt25)
  - [x] core (@virkt25)
  - [x] example-getting-started (@kjdelisle)
  - [x] example-hello-world (@dhmlau)
  - [x] example-log-extension (@virkt25)
  - [x] example-rpc-server (@shimks)
  - [x] metadata (@virkt25)
  - [x] openapi-spec-builder(~@jannyhou~ @dhmlau)
  ~- [ ] openapi-spec~
  ~- [ ] openapi-v2~
  - [x] repository-json-schema (@shimks)
  - [x] repository (@shimks)
  - [x] rest ~(@kjdelisle)~ (@virkt25)
  - [x] testlab (@dhmlau)
- [x] Example repo: loopback4-example-microservices (@b-admike)

**Comment by dhmlau** [comment]
- Crafting LoopBack doc: example repo links are out of date. 
   - Example for application developer: http://loopback.io/doc/en/lb4/Crafting-LoopBack-4.html#example-for-application-developers
   - Example for extension developer: http://loopback.io/doc/en/lb4/Crafting-LoopBack-4.html#example-for-extension-developers

**Comment by kjdelisle** [comment]
Rejecting

We need to split this up into separate tasks so that we can assign the functional areas/modules to their corresponding experts (since they should be the ones ensuring the documentation is accurate).

For other areas that aren't modules, we should have a separate spike that the team can work on as necessary.

**Comment by jannyHou** [comment]
A personal opinion: based on our current progress of upgrading from v2-v3, I would suggest don't spend too much effort on reviewing routing decorator `@param` since it's going to be refactored soon. Any document change/clarification will be done as part of the upgrade story.

**Comment by jannyHou** [comment]
the packages I am familiar with:
- openapi-spec-builder
- openapi-spec
- openapi-v2
the page I am familiar with:
- Language-related concepts
  - mixin
- Key concepts
  - decorators

Also a suggestion: maybe we can split the key concepts into sub items.

**Comment by kjdelisle** [comment]
I started creating some of these items as we discussed in the meeting, but in hindsight, it's starting to feel way too bureaucratic and bloated. I'm just going to regroom this PR to make sure it's clear enough regarding expectations instead of making more issues.

**Comment by dhmlau** [comment]
@kjdelisle , I've added one more item for checking the only standalone example repo `loopback4-example-microservices`.  
According to [this PR in that repo](https://github.com/strongloop/loopback4-example-microservices/pull/78), it doesn't seem like the example is working.  
cc @b-admike

**Comment by kjdelisle** [comment]
I don't think this is a spike, given that it involves doing a whole bunch of work to fix things, and only involves creating new issues when complex problems arise.

**Comment by dhmlau** [comment]
sounds good to me

**Comment by shimks** [comment]
@strongloop/sq-lb-apex Should we also introduce '80 chars per lines' rules to each pages if needed as part of this task?

**Comment by jannyHou** [comment]
After released OpenAPI 3 PRs, we need to update all the docs that contain controller decorators usage, and the OpenAPI specs. For people grab new tasks from this story, please also update V3 changes according to blog https://github.com/strongloop/strongloop.com/pull/113.
The contents in blog PR need polish but all the technical details/user stories are done. So we can use it as the reference when updating docs.

I will also update this comment in this story's description.

**Comment by jannyHou** [comment]
cc @strongloop/loopback-next 
After released OpenAPI 3 PRs, we need to update all the docs that contain controller decorators usage, and the OpenAPI specs. For people grab new tasks from this story, please also update V3 changes according to blog https://github.com/strongloop/strongloop.com/pull/113.
The contents in blog PR need polish but all the technical details/user stories are done. So we can use it as the reference when updating docs.

I will also update this comment in this story's description.

**Comment by kjdelisle** [comment]
@jannyHou If you know what changes need to be made to the documentation, shouldn't that mean that you'd be the one to make them? Others might not know what to change!

**Comment by jannyHou** [comment]
@kjdelisle I write the blog as the migration guide for team.
And I have pointed out the fact several times: the scope of updating all docs is too huge, I am not able to handle all by myself in a reasonable time.
And I also said I need team's help on docs, if you don't agree you should have said it earlier, or bring a plan of how to divide the task.

**Comment by dhmlau** [comment]
For the **Reference** section, there are quite a lot of content need to be updated.  #1118 is opened.  However, #956 was opened to discuss whether we need this page at all.

**Comment by shimks** [comment]
While going through `best practices` (and partly `testing-your-application`), I raised a concern that these should be shelved in this issue: https://github.com/strongloop/loopback-next/issues/1094

**Comment by shimks** [comment]
I want to expand out the `key concepts` section since there's close to 10 pages to cover here. @strongloop/lb-next-dev what does everyone think?

**Comment by shimks** [comment]
ps. i didn't unassign kevin :( github is lying

**Comment by virkt25** [comment]
@shimks great idea. Done :)

**Comment by shimks** [comment]
One question that wasn't discussed in the grooming: if a page is deemed outdated and needs a rework, what do we do to the page before creating an issue for the rework? If a code snippet no longer works/compiles, do we:

- fix the code so that it works?
- Or do we slap on a notice saying that the page is outdated and leave it alone?

**Comment by virkt25** [comment]
Depends on the amount of effort. What page? 

That said if it will require significant updates to even make the code work then just make an issue and bring it up for prioritization. If the content itself needs to be updated then go with creating a new issue.

**Comment by shimks** [comment]
The question rose up while I was looking over `Controller.md`: it's all about making a controller using the top-down approach (making a spec first instead of having it automatically generated). I think for that page itself, it's fine to do a menial amount of work to make the code work and have an issue to replace the content.

But if you take a look at a giant like `Best Practices`, it's hard to make these menial code changes to the code snippets when multiple code snippets are building on top of a single outdated concept that's no longer supported.

I guess I answered my first half of the question there though. But for the second part (docs that need overhaul), I guess it's rather specific to the pages. For example, you deemed that `Extending-LoopBack` needed to be overhauled, but that page probably doesn't have a lot of things that need fixing in terms of making the code work. But for `Best-practices-with-LoopBack`, that thing is a hard subject to tackle both content-wise and concept-wise.

**Comment by shimks** [comment]
@dhmlau I don't recall seeing a PR for `openapi-spec-builder` README. Has it already been done as part of @jannyHou's work?

**Comment by shimks** [comment]
Closing as done
